// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/search/search.proto

package searchv1

import (
	shared "github.com/studyguides-com/study-guides-api/api/v1/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Context       shared.ContextType     `protobuf:"varint,2,opt,name=context,proto3,enum=shared.v1.ContextType" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_v1_search_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_search_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_v1_search_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetContext() shared.ContextType {
	if x != nil {
		return x.Context
	}
	return shared.ContextType(0)
}

type SearchResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Results       []*shared.TagSearchResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_v1_search_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_search_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_v1_search_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResponse) GetResults() []*shared.TagSearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_v1_search_search_proto protoreflect.FileDescriptor

const file_v1_search_search_proto_rawDesc = "" +
	"\n" +
	"\x16v1/search/search.proto\x12\tsearch.v1\x1a\x1fv1/shared/tagsearchresult.proto\x1a\x1bv1/shared/contexttype.proto\"W\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x120\n" +
	"\acontext\x18\x02 \x01(\x0e2\x16.shared.v1.ContextTypeR\acontext\"F\n" +
	"\x0eSearchResponse\x124\n" +
	"\aresults\x18\x01 \x03(\v2\x1a.shared.v1.TagSearchResultR\aresults2N\n" +
	"\rSearchService\x12=\n" +
	"\x06Search\x12\x18.search.v1.SearchRequest\x1a\x19.search.v1.SearchResponseBDZBgithub.com/studyguides-com/study-guides-api/api/v1/search;searchv1b\x06proto3"

var (
	file_v1_search_search_proto_rawDescOnce sync.Once
	file_v1_search_search_proto_rawDescData []byte
)

func file_v1_search_search_proto_rawDescGZIP() []byte {
	file_v1_search_search_proto_rawDescOnce.Do(func() {
		file_v1_search_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_search_search_proto_rawDesc), len(file_v1_search_search_proto_rawDesc)))
	})
	return file_v1_search_search_proto_rawDescData
}

var file_v1_search_search_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_search_search_proto_goTypes = []any{
	(*SearchRequest)(nil),          // 0: search.v1.SearchRequest
	(*SearchResponse)(nil),         // 1: search.v1.SearchResponse
	(shared.ContextType)(0),        // 2: shared.v1.ContextType
	(*shared.TagSearchResult)(nil), // 3: shared.v1.TagSearchResult
}
var file_v1_search_search_proto_depIdxs = []int32{
	2, // 0: search.v1.SearchRequest.context:type_name -> shared.v1.ContextType
	3, // 1: search.v1.SearchResponse.results:type_name -> shared.v1.TagSearchResult
	0, // 2: search.v1.SearchService.Search:input_type -> search.v1.SearchRequest
	1, // 3: search.v1.SearchService.Search:output_type -> search.v1.SearchResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_search_search_proto_init() }
func file_v1_search_search_proto_init() {
	if File_v1_search_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_search_search_proto_rawDesc), len(file_v1_search_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_search_search_proto_goTypes,
		DependencyIndexes: file_v1_search_search_proto_depIdxs,
		MessageInfos:      file_v1_search_search_proto_msgTypes,
	}.Build()
	File_v1_search_search_proto = out.File
	file_v1_search_search_proto_goTypes = nil
	file_v1_search_search_proto_depIdxs = nil
}
