// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/search/search.proto

package searchv1

import (
	shared "github.com/studyguides-com/study-guides-api/api/v1/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Context       shared.ContextType     `protobuf:"varint,2,opt,name=context,proto3,enum=shared.v1.ContextType" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTagsRequest) Reset() {
	*x = SearchTagsRequest{}
	mi := &file_v1_search_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTagsRequest) ProtoMessage() {}

func (x *SearchTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_search_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTagsRequest.ProtoReflect.Descriptor instead.
func (*SearchTagsRequest) Descriptor() ([]byte, []int) {
	return file_v1_search_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchTagsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchTagsRequest) GetContext() shared.ContextType {
	if x != nil {
		return x.Context
	}
	return shared.ContextType(0)
}

type SearchTagsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Results       []*shared.TagSearchResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTagsResponse) Reset() {
	*x = SearchTagsResponse{}
	mi := &file_v1_search_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTagsResponse) ProtoMessage() {}

func (x *SearchTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_search_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTagsResponse.ProtoReflect.Descriptor instead.
func (*SearchTagsResponse) Descriptor() ([]byte, []int) {
	return file_v1_search_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchTagsResponse) GetResults() []*shared.TagSearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type SearchUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersRequest) Reset() {
	*x = SearchUsersRequest{}
	mi := &file_v1_search_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersRequest) ProtoMessage() {}

func (x *SearchUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_search_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersRequest.ProtoReflect.Descriptor instead.
func (*SearchUsersRequest) Descriptor() ([]byte, []int) {
	return file_v1_search_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchUsersRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SearchUsersResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Results       []*shared.UserSearchResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersResponse) Reset() {
	*x = SearchUsersResponse{}
	mi := &file_v1_search_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersResponse) ProtoMessage() {}

func (x *SearchUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_search_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersResponse.ProtoReflect.Descriptor instead.
func (*SearchUsersResponse) Descriptor() ([]byte, []int) {
	return file_v1_search_search_proto_rawDescGZIP(), []int{3}
}

func (x *SearchUsersResponse) GetResults() []*shared.UserSearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type ListIndexesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIndexesRequest) Reset() {
	*x = ListIndexesRequest{}
	mi := &file_v1_search_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIndexesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIndexesRequest) ProtoMessage() {}

func (x *ListIndexesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_search_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIndexesRequest.ProtoReflect.Descriptor instead.
func (*ListIndexesRequest) Descriptor() ([]byte, []int) {
	return file_v1_search_search_proto_rawDescGZIP(), []int{4}
}

func (x *ListIndexesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type ListIndexesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Indexes       []string               `protobuf:"bytes,1,rep,name=indexes,proto3" json:"indexes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIndexesResponse) Reset() {
	*x = ListIndexesResponse{}
	mi := &file_v1_search_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIndexesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIndexesResponse) ProtoMessage() {}

func (x *ListIndexesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_search_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIndexesResponse.ProtoReflect.Descriptor instead.
func (*ListIndexesResponse) Descriptor() ([]byte, []int) {
	return file_v1_search_search_proto_rawDescGZIP(), []int{5}
}

func (x *ListIndexesResponse) GetIndexes() []string {
	if x != nil {
		return x.Indexes
	}
	return nil
}

var File_v1_search_search_proto protoreflect.FileDescriptor

const file_v1_search_search_proto_rawDesc = "" +
	"\n" +
	"\x16v1/search/search.proto\x12\tsearch.v1\x1a\x1fv1/shared/tagsearchresult.proto\x1a\x1bv1/shared/contexttype.proto\x1a v1/shared/usersearchresult.proto\"[\n" +
	"\x11SearchTagsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x120\n" +
	"\acontext\x18\x02 \x01(\x0e2\x16.shared.v1.ContextTypeR\acontext\"J\n" +
	"\x12SearchTagsResponse\x124\n" +
	"\aresults\x18\x01 \x03(\v2\x1a.shared.v1.TagSearchResultR\aresults\"*\n" +
	"\x12SearchUsersRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"L\n" +
	"\x13SearchUsersResponse\x125\n" +
	"\aresults\x18\x01 \x03(\v2\x1b.shared.v1.UserSearchResultR\aresults\"*\n" +
	"\x12ListIndexesRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"/\n" +
	"\x13ListIndexesResponse\x12\x18\n" +
	"\aindexes\x18\x01 \x03(\tR\aindexes2\xf6\x01\n" +
	"\rSearchService\x12I\n" +
	"\n" +
	"SearchTags\x12\x1c.search.v1.SearchTagsRequest\x1a\x1d.search.v1.SearchTagsResponse\x12L\n" +
	"\vSearchUsers\x12\x1d.search.v1.SearchUsersRequest\x1a\x1e.search.v1.SearchUsersResponse\x12L\n" +
	"\vListIndexes\x12\x1d.search.v1.ListIndexesRequest\x1a\x1e.search.v1.ListIndexesResponseBDZBgithub.com/studyguides-com/study-guides-api/api/v1/search;searchv1b\x06proto3"

var (
	file_v1_search_search_proto_rawDescOnce sync.Once
	file_v1_search_search_proto_rawDescData []byte
)

func file_v1_search_search_proto_rawDescGZIP() []byte {
	file_v1_search_search_proto_rawDescOnce.Do(func() {
		file_v1_search_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_search_search_proto_rawDesc), len(file_v1_search_search_proto_rawDesc)))
	})
	return file_v1_search_search_proto_rawDescData
}

var file_v1_search_search_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_v1_search_search_proto_goTypes = []any{
	(*SearchTagsRequest)(nil),       // 0: search.v1.SearchTagsRequest
	(*SearchTagsResponse)(nil),      // 1: search.v1.SearchTagsResponse
	(*SearchUsersRequest)(nil),      // 2: search.v1.SearchUsersRequest
	(*SearchUsersResponse)(nil),     // 3: search.v1.SearchUsersResponse
	(*ListIndexesRequest)(nil),      // 4: search.v1.ListIndexesRequest
	(*ListIndexesResponse)(nil),     // 5: search.v1.ListIndexesResponse
	(shared.ContextType)(0),         // 6: shared.v1.ContextType
	(*shared.TagSearchResult)(nil),  // 7: shared.v1.TagSearchResult
	(*shared.UserSearchResult)(nil), // 8: shared.v1.UserSearchResult
}
var file_v1_search_search_proto_depIdxs = []int32{
	6, // 0: search.v1.SearchTagsRequest.context:type_name -> shared.v1.ContextType
	7, // 1: search.v1.SearchTagsResponse.results:type_name -> shared.v1.TagSearchResult
	8, // 2: search.v1.SearchUsersResponse.results:type_name -> shared.v1.UserSearchResult
	0, // 3: search.v1.SearchService.SearchTags:input_type -> search.v1.SearchTagsRequest
	2, // 4: search.v1.SearchService.SearchUsers:input_type -> search.v1.SearchUsersRequest
	4, // 5: search.v1.SearchService.ListIndexes:input_type -> search.v1.ListIndexesRequest
	1, // 6: search.v1.SearchService.SearchTags:output_type -> search.v1.SearchTagsResponse
	3, // 7: search.v1.SearchService.SearchUsers:output_type -> search.v1.SearchUsersResponse
	5, // 8: search.v1.SearchService.ListIndexes:output_type -> search.v1.ListIndexesResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_search_search_proto_init() }
func file_v1_search_search_proto_init() {
	if File_v1_search_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_search_search_proto_rawDesc), len(file_v1_search_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_search_search_proto_goTypes,
		DependencyIndexes: file_v1_search_search_proto_depIdxs,
		MessageInfos:      file_v1_search_search_proto_msgTypes,
	}.Build()
	File_v1_search_search_proto = out.File
	file_v1_search_search_proto_goTypes = nil
	file_v1_search_search_proto_depIdxs = nil
}
