// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: search/tag_path.proto

package search

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TagPath struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagPath) Reset() {
	*x = TagPath{}
	mi := &file_search_tag_path_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagPath) ProtoMessage() {}

func (x *TagPath) ProtoReflect() protoreflect.Message {
	mi := &file_search_tag_path_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagPath.ProtoReflect.Descriptor instead.
func (*TagPath) Descriptor() ([]byte, []int) {
	return file_search_tag_path_proto_rawDescGZIP(), []int{0}
}

func (x *TagPath) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TagPath) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagPath) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_search_tag_path_proto protoreflect.FileDescriptor

const file_search_tag_path_proto_rawDesc = "" +
	"\n" +
	"\x15search/tag_path.proto\x12\x06search\"A\n" +
	"\aTagPath\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04typeBEZCgithub.com/studyguides-com/study-guides-api/api/study/search;searchb\x06proto3"

var (
	file_search_tag_path_proto_rawDescOnce sync.Once
	file_search_tag_path_proto_rawDescData []byte
)

func file_search_tag_path_proto_rawDescGZIP() []byte {
	file_search_tag_path_proto_rawDescOnce.Do(func() {
		file_search_tag_path_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_search_tag_path_proto_rawDesc), len(file_search_tag_path_proto_rawDesc)))
	})
	return file_search_tag_path_proto_rawDescData
}

var file_search_tag_path_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_search_tag_path_proto_goTypes = []any{
	(*TagPath)(nil), // 0: search.TagPath
}
var file_search_tag_path_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_search_tag_path_proto_init() }
func file_search_tag_path_proto_init() {
	if File_search_tag_path_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_tag_path_proto_rawDesc), len(file_search_tag_path_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_search_tag_path_proto_goTypes,
		DependencyIndexes: file_search_tag_path_proto_depIdxs,
		MessageInfos:      file_search_tag_path_proto_msgTypes,
	}.Build()
	File_search_tag_path_proto = out.File
	file_search_tag_path_proto_goTypes = nil
	file_search_tag_path_proto_depIdxs = nil
}
