// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/shared/ancestor.proto

package sharedv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ancestor struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description        string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Hash               string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	TagType            TagType                `protobuf:"varint,4,opt,name=tag_type,json=tagType,proto3,enum=shared.v1.TagType" json:"tag_type,omitempty"`
	NextAncestor       *Ancestor              `protobuf:"bytes,5,opt,name=next_ancestor,json=nextAncestor,proto3" json:"next_ancestor,omitempty"`
	ContentRating      ContentRating          `protobuf:"varint,6,opt,name=content_rating,json=contentRating,proto3,enum=shared.v1.ContentRating" json:"content_rating,omitempty"`
	ContentDescriptors []string               `protobuf:"bytes,7,rep,name=content_descriptors,json=contentDescriptors,proto3" json:"content_descriptors,omitempty"`
	MetaTags           []string               `protobuf:"bytes,8,rep,name=meta_tags,json=metaTags,proto3" json:"meta_tags,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Ancestor) Reset() {
	*x = Ancestor{}
	mi := &file_v1_shared_ancestor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ancestor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ancestor) ProtoMessage() {}

func (x *Ancestor) ProtoReflect() protoreflect.Message {
	mi := &file_v1_shared_ancestor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ancestor.ProtoReflect.Descriptor instead.
func (*Ancestor) Descriptor() ([]byte, []int) {
	return file_v1_shared_ancestor_proto_rawDescGZIP(), []int{0}
}

func (x *Ancestor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Ancestor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Ancestor) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Ancestor) GetTagType() TagType {
	if x != nil {
		return x.TagType
	}
	return TagType_Category
}

func (x *Ancestor) GetNextAncestor() *Ancestor {
	if x != nil {
		return x.NextAncestor
	}
	return nil
}

func (x *Ancestor) GetContentRating() ContentRating {
	if x != nil {
		return x.ContentRating
	}
	return ContentRating_Unspecified
}

func (x *Ancestor) GetContentDescriptors() []string {
	if x != nil {
		return x.ContentDescriptors
	}
	return nil
}

func (x *Ancestor) GetMetaTags() []string {
	if x != nil {
		return x.MetaTags
	}
	return nil
}

var File_v1_shared_ancestor_proto protoreflect.FileDescriptor

const file_v1_shared_ancestor_proto_rawDesc = "" +
	"\n" +
	"\x18v1/shared/ancestor.proto\x12\tshared.v1\x1a\x1dv1/shared/contentrating.proto\x1a\x17v1/shared/tagtype.proto\"\xcc\x02\n" +
	"\bAncestor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12-\n" +
	"\btag_type\x18\x04 \x01(\x0e2\x12.shared.v1.TagTypeR\atagType\x128\n" +
	"\rnext_ancestor\x18\x05 \x01(\v2\x13.shared.v1.AncestorR\fnextAncestor\x12?\n" +
	"\x0econtent_rating\x18\x06 \x01(\x0e2\x18.shared.v1.ContentRatingR\rcontentRating\x12/\n" +
	"\x13content_descriptors\x18\a \x03(\tR\x12contentDescriptors\x12\x1b\n" +
	"\tmeta_tags\x18\b \x03(\tR\bmetaTagsBDZBgithub.com/studyguides-com/study-guides-api/api/v1/shared;sharedv1b\x06proto3"

var (
	file_v1_shared_ancestor_proto_rawDescOnce sync.Once
	file_v1_shared_ancestor_proto_rawDescData []byte
)

func file_v1_shared_ancestor_proto_rawDescGZIP() []byte {
	file_v1_shared_ancestor_proto_rawDescOnce.Do(func() {
		file_v1_shared_ancestor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_shared_ancestor_proto_rawDesc), len(file_v1_shared_ancestor_proto_rawDesc)))
	})
	return file_v1_shared_ancestor_proto_rawDescData
}

var file_v1_shared_ancestor_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_shared_ancestor_proto_goTypes = []any{
	(*Ancestor)(nil),   // 0: shared.v1.Ancestor
	(TagType)(0),       // 1: shared.v1.TagType
	(ContentRating)(0), // 2: shared.v1.ContentRating
}
var file_v1_shared_ancestor_proto_depIdxs = []int32{
	1, // 0: shared.v1.Ancestor.tag_type:type_name -> shared.v1.TagType
	0, // 1: shared.v1.Ancestor.next_ancestor:type_name -> shared.v1.Ancestor
	2, // 2: shared.v1.Ancestor.content_rating:type_name -> shared.v1.ContentRating
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_shared_ancestor_proto_init() }
func file_v1_shared_ancestor_proto_init() {
	if File_v1_shared_ancestor_proto != nil {
		return
	}
	file_v1_shared_contentrating_proto_init()
	file_v1_shared_tagtype_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_shared_ancestor_proto_rawDesc), len(file_v1_shared_ancestor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_shared_ancestor_proto_goTypes,
		DependencyIndexes: file_v1_shared_ancestor_proto_depIdxs,
		MessageInfos:      file_v1_shared_ancestor_proto_msgTypes,
	}.Build()
	File_v1_shared_ancestor_proto = out.File
	file_v1_shared_ancestor_proto_goTypes = nil
	file_v1_shared_ancestor_proto_depIdxs = nil
}
