// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/shared/bundle.proto

package sharedv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bundle represents a study guide bundle in the database
type Bundle struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShortId        string                 `protobuf:"bytes,2,opt,name=short_id,json=shortId,proto3" json:"short_id,omitempty"`
	ParserType     string                 `protobuf:"bytes,3,opt,name=parser_type,json=parserType,proto3" json:"parser_type,omitempty"`
	Title          string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Payload        []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`                         // Using bytes for jsonb
	GobPayload     []byte                 `protobuf:"bytes,6,opt,name=gob_payload,json=gobPayload,proto3" json:"gob_payload,omitempty"` // Using bytes for gob encoding
	ExportedToDev  bool                   `protobuf:"varint,7,opt,name=exported_to_dev,json=exportedToDev,proto3" json:"exported_to_dev,omitempty"`
	ExportedToTest bool                   `protobuf:"varint,8,opt,name=exported_to_test,json=exportedToTest,proto3" json:"exported_to_test,omitempty"`
	ExportedToProd bool                   `protobuf:"varint,9,opt,name=exported_to_prod,json=exportedToProd,proto3" json:"exported_to_prod,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	AssistedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=assisted_at,json=assistedAt,proto3" json:"assisted_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Bundle) Reset() {
	*x = Bundle{}
	mi := &file_v1_shared_bundle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bundle) ProtoMessage() {}

func (x *Bundle) ProtoReflect() protoreflect.Message {
	mi := &file_v1_shared_bundle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bundle.ProtoReflect.Descriptor instead.
func (*Bundle) Descriptor() ([]byte, []int) {
	return file_v1_shared_bundle_proto_rawDescGZIP(), []int{0}
}

func (x *Bundle) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bundle) GetShortId() string {
	if x != nil {
		return x.ShortId
	}
	return ""
}

func (x *Bundle) GetParserType() string {
	if x != nil {
		return x.ParserType
	}
	return ""
}

func (x *Bundle) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Bundle) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Bundle) GetGobPayload() []byte {
	if x != nil {
		return x.GobPayload
	}
	return nil
}

func (x *Bundle) GetExportedToDev() bool {
	if x != nil {
		return x.ExportedToDev
	}
	return false
}

func (x *Bundle) GetExportedToTest() bool {
	if x != nil {
		return x.ExportedToTest
	}
	return false
}

func (x *Bundle) GetExportedToProd() bool {
	if x != nil {
		return x.ExportedToProd
	}
	return false
}

func (x *Bundle) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Bundle) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Bundle) GetAssistedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AssistedAt
	}
	return nil
}

var File_v1_shared_bundle_proto protoreflect.FileDescriptor

const file_v1_shared_bundle_proto_rawDesc = "" +
	"\n" +
	"\x16v1/shared/bundle.proto\x12\tshared.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd4\x03\n" +
	"\x06Bundle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bshort_id\x18\x02 \x01(\tR\ashortId\x12\x1f\n" +
	"\vparser_type\x18\x03 \x01(\tR\n" +
	"parserType\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12\x1f\n" +
	"\vgob_payload\x18\x06 \x01(\fR\n" +
	"gobPayload\x12&\n" +
	"\x0fexported_to_dev\x18\a \x01(\bR\rexportedToDev\x12(\n" +
	"\x10exported_to_test\x18\b \x01(\bR\x0eexportedToTest\x12(\n" +
	"\x10exported_to_prod\x18\t \x01(\bR\x0eexportedToProd\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12;\n" +
	"\vassisted_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"assistedAtBDZBgithub.com/studyguides-com/study-guides-api/api/v1/shared;sharedv1b\x06proto3"

var (
	file_v1_shared_bundle_proto_rawDescOnce sync.Once
	file_v1_shared_bundle_proto_rawDescData []byte
)

func file_v1_shared_bundle_proto_rawDescGZIP() []byte {
	file_v1_shared_bundle_proto_rawDescOnce.Do(func() {
		file_v1_shared_bundle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_shared_bundle_proto_rawDesc), len(file_v1_shared_bundle_proto_rawDesc)))
	})
	return file_v1_shared_bundle_proto_rawDescData
}

var file_v1_shared_bundle_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_shared_bundle_proto_goTypes = []any{
	(*Bundle)(nil),                // 0: shared.v1.Bundle
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_v1_shared_bundle_proto_depIdxs = []int32{
	1, // 0: shared.v1.Bundle.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: shared.v1.Bundle.updated_at:type_name -> google.protobuf.Timestamp
	1, // 2: shared.v1.Bundle.assisted_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_shared_bundle_proto_init() }
func file_v1_shared_bundle_proto_init() {
	if File_v1_shared_bundle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_shared_bundle_proto_rawDesc), len(file_v1_shared_bundle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_shared_bundle_proto_goTypes,
		DependencyIndexes: file_v1_shared_bundle_proto_depIdxs,
		MessageInfos:      file_v1_shared_bundle_proto_msgTypes,
	}.Build()
	File_v1_shared_bundle_proto = out.File
	file_v1_shared_bundle_proto_goTypes = nil
	file_v1_shared_bundle_proto_depIdxs = nil
}
