// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/shared/contexttype.proto

package sharedv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContextType int32

const (
	ContextType_CONTEXT_TYPE_COLLEGES       ContextType = 0
	ContextType_CONTEXT_TYPE_CERTIFICATIONS ContextType = 1
	ContextType_CONTEXT_TYPE_ENTRANCE_EXAMS ContextType = 2
	ContextType_CONTEXT_TYPE_AP_EXAMS       ContextType = 3
	ContextType_CONTEXT_TYPE_DOD            ContextType = 4
	ContextType_CONTEXT_TYPE_ALL            ContextType = 5
)

// Enum value maps for ContextType.
var (
	ContextType_name = map[int32]string{
		0: "CONTEXT_TYPE_COLLEGES",
		1: "CONTEXT_TYPE_CERTIFICATIONS",
		2: "CONTEXT_TYPE_ENTRANCE_EXAMS",
		3: "CONTEXT_TYPE_AP_EXAMS",
		4: "CONTEXT_TYPE_DOD",
		5: "CONTEXT_TYPE_ALL",
	}
	ContextType_value = map[string]int32{
		"CONTEXT_TYPE_COLLEGES":       0,
		"CONTEXT_TYPE_CERTIFICATIONS": 1,
		"CONTEXT_TYPE_ENTRANCE_EXAMS": 2,
		"CONTEXT_TYPE_AP_EXAMS":       3,
		"CONTEXT_TYPE_DOD":            4,
		"CONTEXT_TYPE_ALL":            5,
	}
)

func (x ContextType) Enum() *ContextType {
	p := new(ContextType)
	*p = x
	return p
}

func (x ContextType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContextType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_shared_contexttype_proto_enumTypes[0].Descriptor()
}

func (ContextType) Type() protoreflect.EnumType {
	return &file_v1_shared_contexttype_proto_enumTypes[0]
}

func (x ContextType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContextType.Descriptor instead.
func (ContextType) EnumDescriptor() ([]byte, []int) {
	return file_v1_shared_contexttype_proto_rawDescGZIP(), []int{0}
}

var File_v1_shared_contexttype_proto protoreflect.FileDescriptor

const file_v1_shared_contexttype_proto_rawDesc = "" +
	"\n" +
	"\x1bv1/shared/contexttype.proto\x12\tshared.v1*\xb1\x01\n" +
	"\vContextType\x12\x19\n" +
	"\x15CONTEXT_TYPE_COLLEGES\x10\x00\x12\x1f\n" +
	"\x1bCONTEXT_TYPE_CERTIFICATIONS\x10\x01\x12\x1f\n" +
	"\x1bCONTEXT_TYPE_ENTRANCE_EXAMS\x10\x02\x12\x19\n" +
	"\x15CONTEXT_TYPE_AP_EXAMS\x10\x03\x12\x14\n" +
	"\x10CONTEXT_TYPE_DOD\x10\x04\x12\x14\n" +
	"\x10CONTEXT_TYPE_ALL\x10\x05BDZBgithub.com/studyguides-com/study-guides-api/api/v1/shared;sharedv1b\x06proto3"

var (
	file_v1_shared_contexttype_proto_rawDescOnce sync.Once
	file_v1_shared_contexttype_proto_rawDescData []byte
)

func file_v1_shared_contexttype_proto_rawDescGZIP() []byte {
	file_v1_shared_contexttype_proto_rawDescOnce.Do(func() {
		file_v1_shared_contexttype_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_shared_contexttype_proto_rawDesc), len(file_v1_shared_contexttype_proto_rawDesc)))
	})
	return file_v1_shared_contexttype_proto_rawDescData
}

var file_v1_shared_contexttype_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_shared_contexttype_proto_goTypes = []any{
	(ContextType)(0), // 0: shared.v1.ContextType
}
var file_v1_shared_contexttype_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_shared_contexttype_proto_init() }
func file_v1_shared_contexttype_proto_init() {
	if File_v1_shared_contexttype_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_shared_contexttype_proto_rawDesc), len(file_v1_shared_contexttype_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_shared_contexttype_proto_goTypes,
		DependencyIndexes: file_v1_shared_contexttype_proto_depIdxs,
		EnumInfos:         file_v1_shared_contexttype_proto_enumTypes,
	}.Build()
	File_v1_shared_contexttype_proto = out.File
	file_v1_shared_contexttype_proto_goTypes = nil
	file_v1_shared_contexttype_proto_depIdxs = nil
}
