// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/shared/contentrating.proto

package sharedv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContentRating int32

const (
	ContentRating_CONTENT_RATING_UNSPECIFIED ContentRating = 0
	ContentRating_CONTENT_RATING_EVERYONE    ContentRating = 1
	ContentRating_CONTENT_RATING_EVERYONE_10 ContentRating = 2
	ContentRating_CONTENT_RATING_TEEN        ContentRating = 3
	ContentRating_CONTENT_RATING_MATURE      ContentRating = 4
	ContentRating_CONTENT_RATING_ADULTS_ONLY ContentRating = 5
	ContentRating_CONTENT_RATING_PENDING     ContentRating = 6
)

// Enum value maps for ContentRating.
var (
	ContentRating_name = map[int32]string{
		0: "CONTENT_RATING_UNSPECIFIED",
		1: "CONTENT_RATING_EVERYONE",
		2: "CONTENT_RATING_EVERYONE_10",
		3: "CONTENT_RATING_TEEN",
		4: "CONTENT_RATING_MATURE",
		5: "CONTENT_RATING_ADULTS_ONLY",
		6: "CONTENT_RATING_PENDING",
	}
	ContentRating_value = map[string]int32{
		"CONTENT_RATING_UNSPECIFIED": 0,
		"CONTENT_RATING_EVERYONE":    1,
		"CONTENT_RATING_EVERYONE_10": 2,
		"CONTENT_RATING_TEEN":        3,
		"CONTENT_RATING_MATURE":      4,
		"CONTENT_RATING_ADULTS_ONLY": 5,
		"CONTENT_RATING_PENDING":     6,
	}
)

func (x ContentRating) Enum() *ContentRating {
	p := new(ContentRating)
	*p = x
	return p
}

func (x ContentRating) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentRating) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_shared_contentrating_proto_enumTypes[0].Descriptor()
}

func (ContentRating) Type() protoreflect.EnumType {
	return &file_v1_shared_contentrating_proto_enumTypes[0]
}

func (x ContentRating) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentRating.Descriptor instead.
func (ContentRating) EnumDescriptor() ([]byte, []int) {
	return file_v1_shared_contentrating_proto_rawDescGZIP(), []int{0}
}

var File_v1_shared_contentrating_proto protoreflect.FileDescriptor

const file_v1_shared_contentrating_proto_rawDesc = "" +
	"\n" +
	"\x1dv1/shared/contentrating.proto\x12\tshared.v1*\xdc\x01\n" +
	"\rContentRating\x12\x1e\n" +
	"\x1aCONTENT_RATING_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17CONTENT_RATING_EVERYONE\x10\x01\x12\x1e\n" +
	"\x1aCONTENT_RATING_EVERYONE_10\x10\x02\x12\x17\n" +
	"\x13CONTENT_RATING_TEEN\x10\x03\x12\x19\n" +
	"\x15CONTENT_RATING_MATURE\x10\x04\x12\x1e\n" +
	"\x1aCONTENT_RATING_ADULTS_ONLY\x10\x05\x12\x1a\n" +
	"\x16CONTENT_RATING_PENDING\x10\x06BDZBgithub.com/studyguides-com/study-guides-api/api/v1/shared;sharedv1b\x06proto3"

var (
	file_v1_shared_contentrating_proto_rawDescOnce sync.Once
	file_v1_shared_contentrating_proto_rawDescData []byte
)

func file_v1_shared_contentrating_proto_rawDescGZIP() []byte {
	file_v1_shared_contentrating_proto_rawDescOnce.Do(func() {
		file_v1_shared_contentrating_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_shared_contentrating_proto_rawDesc), len(file_v1_shared_contentrating_proto_rawDesc)))
	})
	return file_v1_shared_contentrating_proto_rawDescData
}

var file_v1_shared_contentrating_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_shared_contentrating_proto_goTypes = []any{
	(ContentRating)(0), // 0: shared.v1.ContentRating
}
var file_v1_shared_contentrating_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_shared_contentrating_proto_init() }
func file_v1_shared_contentrating_proto_init() {
	if File_v1_shared_contentrating_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_shared_contentrating_proto_rawDesc), len(file_v1_shared_contentrating_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_shared_contentrating_proto_goTypes,
		DependencyIndexes: file_v1_shared_contentrating_proto_depIdxs,
		EnumInfos:         file_v1_shared_contentrating_proto_enumTypes,
	}.Build()
	File_v1_shared_contentrating_proto = out.File
	file_v1_shared_contentrating_proto_goTypes = nil
	file_v1_shared_contentrating_proto_depIdxs = nil
}
