// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/shared/contentdescriptortype.proto

package sharedv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContentDescriptorType int32

const (
	ContentDescriptorType_CONTENT_DESCRIPTOR_TYPE_UNSPECIFIED         ContentDescriptorType = 0
	ContentDescriptorType_CONTENT_DESCRIPTOR_TYPE_ALCOHOL_REFERENCE   ContentDescriptorType = 1
	ContentDescriptorType_CONTENT_DESCRIPTOR_TYPE_DRUG_REFERENCE      ContentDescriptorType = 2
	ContentDescriptorType_CONTENT_DESCRIPTOR_TYPE_LANGUAGE            ContentDescriptorType = 3
	ContentDescriptorType_CONTENT_DESCRIPTOR_TYPE_SEXUAL_CONTENT      ContentDescriptorType = 4
	ContentDescriptorType_CONTENT_DESCRIPTOR_TYPE_MEDICAL_TERMINOLOGY ContentDescriptorType = 5
)

// Enum value maps for ContentDescriptorType.
var (
	ContentDescriptorType_name = map[int32]string{
		0: "CONTENT_DESCRIPTOR_TYPE_UNSPECIFIED",
		1: "CONTENT_DESCRIPTOR_TYPE_ALCOHOL_REFERENCE",
		2: "CONTENT_DESCRIPTOR_TYPE_DRUG_REFERENCE",
		3: "CONTENT_DESCRIPTOR_TYPE_LANGUAGE",
		4: "CONTENT_DESCRIPTOR_TYPE_SEXUAL_CONTENT",
		5: "CONTENT_DESCRIPTOR_TYPE_MEDICAL_TERMINOLOGY",
	}
	ContentDescriptorType_value = map[string]int32{
		"CONTENT_DESCRIPTOR_TYPE_UNSPECIFIED":         0,
		"CONTENT_DESCRIPTOR_TYPE_ALCOHOL_REFERENCE":   1,
		"CONTENT_DESCRIPTOR_TYPE_DRUG_REFERENCE":      2,
		"CONTENT_DESCRIPTOR_TYPE_LANGUAGE":            3,
		"CONTENT_DESCRIPTOR_TYPE_SEXUAL_CONTENT":      4,
		"CONTENT_DESCRIPTOR_TYPE_MEDICAL_TERMINOLOGY": 5,
	}
)

func (x ContentDescriptorType) Enum() *ContentDescriptorType {
	p := new(ContentDescriptorType)
	*p = x
	return p
}

func (x ContentDescriptorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentDescriptorType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_shared_contentdescriptortype_proto_enumTypes[0].Descriptor()
}

func (ContentDescriptorType) Type() protoreflect.EnumType {
	return &file_v1_shared_contentdescriptortype_proto_enumTypes[0]
}

func (x ContentDescriptorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentDescriptorType.Descriptor instead.
func (ContentDescriptorType) EnumDescriptor() ([]byte, []int) {
	return file_v1_shared_contentdescriptortype_proto_rawDescGZIP(), []int{0}
}

var File_v1_shared_contentdescriptortype_proto protoreflect.FileDescriptor

const file_v1_shared_contentdescriptortype_proto_rawDesc = "" +
	"\n" +
	"%v1/shared/contentdescriptortype.proto\x12\tshared.v1*\x9e\x02\n" +
	"\x15ContentDescriptorType\x12'\n" +
	"#CONTENT_DESCRIPTOR_TYPE_UNSPECIFIED\x10\x00\x12-\n" +
	")CONTENT_DESCRIPTOR_TYPE_ALCOHOL_REFERENCE\x10\x01\x12*\n" +
	"&CONTENT_DESCRIPTOR_TYPE_DRUG_REFERENCE\x10\x02\x12$\n" +
	" CONTENT_DESCRIPTOR_TYPE_LANGUAGE\x10\x03\x12*\n" +
	"&CONTENT_DESCRIPTOR_TYPE_SEXUAL_CONTENT\x10\x04\x12/\n" +
	"+CONTENT_DESCRIPTOR_TYPE_MEDICAL_TERMINOLOGY\x10\x05BDZBgithub.com/studyguides-com/study-guides-api/api/v1/shared;sharedv1b\x06proto3"

var (
	file_v1_shared_contentdescriptortype_proto_rawDescOnce sync.Once
	file_v1_shared_contentdescriptortype_proto_rawDescData []byte
)

func file_v1_shared_contentdescriptortype_proto_rawDescGZIP() []byte {
	file_v1_shared_contentdescriptortype_proto_rawDescOnce.Do(func() {
		file_v1_shared_contentdescriptortype_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_shared_contentdescriptortype_proto_rawDesc), len(file_v1_shared_contentdescriptortype_proto_rawDesc)))
	})
	return file_v1_shared_contentdescriptortype_proto_rawDescData
}

var file_v1_shared_contentdescriptortype_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_shared_contentdescriptortype_proto_goTypes = []any{
	(ContentDescriptorType)(0), // 0: shared.v1.ContentDescriptorType
}
var file_v1_shared_contentdescriptortype_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_shared_contentdescriptortype_proto_init() }
func file_v1_shared_contentdescriptortype_proto_init() {
	if File_v1_shared_contentdescriptortype_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_shared_contentdescriptortype_proto_rawDesc), len(file_v1_shared_contentdescriptortype_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_shared_contentdescriptortype_proto_goTypes,
		DependencyIndexes: file_v1_shared_contentdescriptortype_proto_depIdxs,
		EnumInfos:         file_v1_shared_contentdescriptortype_proto_enumTypes,
	}.Build()
	File_v1_shared_contentdescriptortype_proto = out.File
	file_v1_shared_contentdescriptortype_proto_goTypes = nil
	file_v1_shared_contentdescriptortype_proto_depIdxs = nil
}
