// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/shared/deckassignment.proto

package sharedv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeckAssignment int32

const (
	DeckAssignment_DIFFICULTY_LEVEL_EASY        DeckAssignment = 0
	DeckAssignment_DIFFICULTY_LEVEL_HARD        DeckAssignment = 1
	DeckAssignment_DIFFICULTY_LEVEL_UNSPECIFIED DeckAssignment = 2
)

// Enum value maps for DeckAssignment.
var (
	DeckAssignment_name = map[int32]string{
		0: "DIFFICULTY_LEVEL_EASY",
		1: "DIFFICULTY_LEVEL_HARD",
		2: "DIFFICULTY_LEVEL_UNSPECIFIED",
	}
	DeckAssignment_value = map[string]int32{
		"DIFFICULTY_LEVEL_EASY":        0,
		"DIFFICULTY_LEVEL_HARD":        1,
		"DIFFICULTY_LEVEL_UNSPECIFIED": 2,
	}
)

func (x DeckAssignment) Enum() *DeckAssignment {
	p := new(DeckAssignment)
	*p = x
	return p
}

func (x DeckAssignment) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeckAssignment) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_shared_deckassignment_proto_enumTypes[0].Descriptor()
}

func (DeckAssignment) Type() protoreflect.EnumType {
	return &file_v1_shared_deckassignment_proto_enumTypes[0]
}

func (x DeckAssignment) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeckAssignment.Descriptor instead.
func (DeckAssignment) EnumDescriptor() ([]byte, []int) {
	return file_v1_shared_deckassignment_proto_rawDescGZIP(), []int{0}
}

var File_v1_shared_deckassignment_proto protoreflect.FileDescriptor

const file_v1_shared_deckassignment_proto_rawDesc = "" +
	"\n" +
	"\x1ev1/shared/deckassignment.proto\x12\tshared.v1*h\n" +
	"\x0eDeckAssignment\x12\x19\n" +
	"\x15DIFFICULTY_LEVEL_EASY\x10\x00\x12\x19\n" +
	"\x15DIFFICULTY_LEVEL_HARD\x10\x01\x12 \n" +
	"\x1cDIFFICULTY_LEVEL_UNSPECIFIED\x10\x02BDZBgithub.com/studyguides-com/study-guides-api/api/v1/shared;sharedv1b\x06proto3"

var (
	file_v1_shared_deckassignment_proto_rawDescOnce sync.Once
	file_v1_shared_deckassignment_proto_rawDescData []byte
)

func file_v1_shared_deckassignment_proto_rawDescGZIP() []byte {
	file_v1_shared_deckassignment_proto_rawDescOnce.Do(func() {
		file_v1_shared_deckassignment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_shared_deckassignment_proto_rawDesc), len(file_v1_shared_deckassignment_proto_rawDesc)))
	})
	return file_v1_shared_deckassignment_proto_rawDescData
}

var file_v1_shared_deckassignment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_shared_deckassignment_proto_goTypes = []any{
	(DeckAssignment)(0), // 0: shared.v1.DeckAssignment
}
var file_v1_shared_deckassignment_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_shared_deckassignment_proto_init() }
func file_v1_shared_deckassignment_proto_init() {
	if File_v1_shared_deckassignment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_shared_deckassignment_proto_rawDesc), len(file_v1_shared_deckassignment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_shared_deckassignment_proto_goTypes,
		DependencyIndexes: file_v1_shared_deckassignment_proto_depIdxs,
		EnumInfos:         file_v1_shared_deckassignment_proto_enumTypes,
	}.Build()
	File_v1_shared_deckassignment_proto = out.File
	file_v1_shared_deckassignment_proto_goTypes = nil
	file_v1_shared_deckassignment_proto_depIdxs = nil
}
