// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/shared/interactiontype.proto

package sharedv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InteractionType int32

const (
	InteractionType_INTERACTION_TYPE_ANSWER_CORRECTLY   InteractionType = 0
	InteractionType_INTERACTION_TYPE_ANSWER_INCORRECTLY InteractionType = 1
	InteractionType_INTERACTION_TYPE_REVEAL             InteractionType = 2
	InteractionType_INTERACTION_TYPE_ANSWER_EASY        InteractionType = 3
	InteractionType_INTERACTION_TYPE_ANSWER_HARD        InteractionType = 4
	InteractionType_INTERACTION_TYPE_VIEW_LEARN_MORE    InteractionType = 5
	InteractionType_INTERACTION_TYPE_VIEW_PASSAGE       InteractionType = 6
	InteractionType_INTERACTION_TYPE_NONE               InteractionType = 7
)

// Enum value maps for InteractionType.
var (
	InteractionType_name = map[int32]string{
		0: "INTERACTION_TYPE_ANSWER_CORRECTLY",
		1: "INTERACTION_TYPE_ANSWER_INCORRECTLY",
		2: "INTERACTION_TYPE_REVEAL",
		3: "INTERACTION_TYPE_ANSWER_EASY",
		4: "INTERACTION_TYPE_ANSWER_HARD",
		5: "INTERACTION_TYPE_VIEW_LEARN_MORE",
		6: "INTERACTION_TYPE_VIEW_PASSAGE",
		7: "INTERACTION_TYPE_NONE",
	}
	InteractionType_value = map[string]int32{
		"INTERACTION_TYPE_ANSWER_CORRECTLY":   0,
		"INTERACTION_TYPE_ANSWER_INCORRECTLY": 1,
		"INTERACTION_TYPE_REVEAL":             2,
		"INTERACTION_TYPE_ANSWER_EASY":        3,
		"INTERACTION_TYPE_ANSWER_HARD":        4,
		"INTERACTION_TYPE_VIEW_LEARN_MORE":    5,
		"INTERACTION_TYPE_VIEW_PASSAGE":       6,
		"INTERACTION_TYPE_NONE":               7,
	}
)

func (x InteractionType) Enum() *InteractionType {
	p := new(InteractionType)
	*p = x
	return p
}

func (x InteractionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InteractionType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_shared_interactiontype_proto_enumTypes[0].Descriptor()
}

func (InteractionType) Type() protoreflect.EnumType {
	return &file_v1_shared_interactiontype_proto_enumTypes[0]
}

func (x InteractionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InteractionType.Descriptor instead.
func (InteractionType) EnumDescriptor() ([]byte, []int) {
	return file_v1_shared_interactiontype_proto_rawDescGZIP(), []int{0}
}

var File_v1_shared_interactiontype_proto protoreflect.FileDescriptor

const file_v1_shared_interactiontype_proto_rawDesc = "" +
	"\n" +
	"\x1fv1/shared/interactiontype.proto\x12\tshared.v1*\xa6\x02\n" +
	"\x0fInteractionType\x12%\n" +
	"!INTERACTION_TYPE_ANSWER_CORRECTLY\x10\x00\x12'\n" +
	"#INTERACTION_TYPE_ANSWER_INCORRECTLY\x10\x01\x12\x1b\n" +
	"\x17INTERACTION_TYPE_REVEAL\x10\x02\x12 \n" +
	"\x1cINTERACTION_TYPE_ANSWER_EASY\x10\x03\x12 \n" +
	"\x1cINTERACTION_TYPE_ANSWER_HARD\x10\x04\x12$\n" +
	" INTERACTION_TYPE_VIEW_LEARN_MORE\x10\x05\x12!\n" +
	"\x1dINTERACTION_TYPE_VIEW_PASSAGE\x10\x06\x12\x19\n" +
	"\x15INTERACTION_TYPE_NONE\x10\aBDZBgithub.com/studyguides-com/study-guides-api/api/v1/shared;sharedv1b\x06proto3"

var (
	file_v1_shared_interactiontype_proto_rawDescOnce sync.Once
	file_v1_shared_interactiontype_proto_rawDescData []byte
)

func file_v1_shared_interactiontype_proto_rawDescGZIP() []byte {
	file_v1_shared_interactiontype_proto_rawDescOnce.Do(func() {
		file_v1_shared_interactiontype_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_shared_interactiontype_proto_rawDesc), len(file_v1_shared_interactiontype_proto_rawDesc)))
	})
	return file_v1_shared_interactiontype_proto_rawDescData
}

var file_v1_shared_interactiontype_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_shared_interactiontype_proto_goTypes = []any{
	(InteractionType)(0), // 0: shared.v1.InteractionType
}
var file_v1_shared_interactiontype_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_shared_interactiontype_proto_init() }
func file_v1_shared_interactiontype_proto_init() {
	if File_v1_shared_interactiontype_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_shared_interactiontype_proto_rawDesc), len(file_v1_shared_interactiontype_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_shared_interactiontype_proto_goTypes,
		DependencyIndexes: file_v1_shared_interactiontype_proto_depIdxs,
		EnumInfos:         file_v1_shared_interactiontype_proto_enumTypes,
	}.Build()
	File_v1_shared_interactiontype_proto = out.File
	file_v1_shared_interactiontype_proto_goTypes = nil
	file_v1_shared_interactiontype_proto_depIdxs = nil
}
