// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/shared/interactiontype.proto

package sharedv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InteractionType int32

const (
	InteractionType_AnswerCorrectly   InteractionType = 0
	InteractionType_AnswerIncorrectly InteractionType = 1
	InteractionType_Reveal            InteractionType = 2
	InteractionType_AnswerEasy        InteractionType = 3
	InteractionType_AnswerHard        InteractionType = 4
	InteractionType_ViewLearnMore     InteractionType = 5
	InteractionType_ViewPassage       InteractionType = 6
	InteractionType_InteractionNone   InteractionType = 7
)

// Enum value maps for InteractionType.
var (
	InteractionType_name = map[int32]string{
		0: "AnswerCorrectly",
		1: "AnswerIncorrectly",
		2: "Reveal",
		3: "AnswerEasy",
		4: "AnswerHard",
		5: "ViewLearnMore",
		6: "ViewPassage",
		7: "InteractionNone",
	}
	InteractionType_value = map[string]int32{
		"AnswerCorrectly":   0,
		"AnswerIncorrectly": 1,
		"Reveal":            2,
		"AnswerEasy":        3,
		"AnswerHard":        4,
		"ViewLearnMore":     5,
		"ViewPassage":       6,
		"InteractionNone":   7,
	}
)

func (x InteractionType) Enum() *InteractionType {
	p := new(InteractionType)
	*p = x
	return p
}

func (x InteractionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InteractionType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_shared_interactiontype_proto_enumTypes[0].Descriptor()
}

func (InteractionType) Type() protoreflect.EnumType {
	return &file_v1_shared_interactiontype_proto_enumTypes[0]
}

func (x InteractionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InteractionType.Descriptor instead.
func (InteractionType) EnumDescriptor() ([]byte, []int) {
	return file_v1_shared_interactiontype_proto_rawDescGZIP(), []int{0}
}

var File_v1_shared_interactiontype_proto protoreflect.FileDescriptor

const file_v1_shared_interactiontype_proto_rawDesc = "" +
	"\n" +
	"\x1fv1/shared/interactiontype.proto\x12\tshared.v1*\xa2\x01\n" +
	"\x0fInteractionType\x12\x13\n" +
	"\x0fAnswerCorrectly\x10\x00\x12\x15\n" +
	"\x11AnswerIncorrectly\x10\x01\x12\n" +
	"\n" +
	"\x06Reveal\x10\x02\x12\x0e\n" +
	"\n" +
	"AnswerEasy\x10\x03\x12\x0e\n" +
	"\n" +
	"AnswerHard\x10\x04\x12\x11\n" +
	"\rViewLearnMore\x10\x05\x12\x0f\n" +
	"\vViewPassage\x10\x06\x12\x13\n" +
	"\x0fInteractionNone\x10\aBDZBgithub.com/studyguides-com/study-guides-api/api/v1/shared;sharedv1b\x06proto3"

var (
	file_v1_shared_interactiontype_proto_rawDescOnce sync.Once
	file_v1_shared_interactiontype_proto_rawDescData []byte
)

func file_v1_shared_interactiontype_proto_rawDescGZIP() []byte {
	file_v1_shared_interactiontype_proto_rawDescOnce.Do(func() {
		file_v1_shared_interactiontype_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_shared_interactiontype_proto_rawDesc), len(file_v1_shared_interactiontype_proto_rawDesc)))
	})
	return file_v1_shared_interactiontype_proto_rawDescData
}

var file_v1_shared_interactiontype_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_shared_interactiontype_proto_goTypes = []any{
	(InteractionType)(0), // 0: shared.v1.InteractionType
}
var file_v1_shared_interactiontype_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_shared_interactiontype_proto_init() }
func file_v1_shared_interactiontype_proto_init() {
	if File_v1_shared_interactiontype_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_shared_interactiontype_proto_rawDesc), len(file_v1_shared_interactiontype_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_shared_interactiontype_proto_goTypes,
		DependencyIndexes: file_v1_shared_interactiontype_proto_depIdxs,
		EnumInfos:         file_v1_shared_interactiontype_proto_enumTypes,
	}.Build()
	File_v1_shared_interactiontype_proto = out.File
	file_v1_shared_interactiontype_proto_goTypes = nil
	file_v1_shared_interactiontype_proto_depIdxs = nil
}
