// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/shared/node.proto

package sharedv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Level         int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Parent        *Node                  `protobuf:"bytes,5,opt,name=parent,proto3" json:"parent,omitempty"`
	Questions     []*Prompt              `protobuf:"bytes,6,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_v1_shared_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_v1_shared_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_v1_shared_node_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Node) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Node) GetParent() *Node {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *Node) GetQuestions() []*Prompt {
	if x != nil {
		return x.Questions
	}
	return nil
}

var File_v1_shared_node_proto protoreflect.FileDescriptor

const file_v1_shared_node_proto_rawDesc = "" +
	"\n" +
	"\x14v1/shared/node.proto\x12\tshared.v1\x1a\x16v1/shared/prompt.proto\"\xae\x01\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12'\n" +
	"\x06parent\x18\x05 \x01(\v2\x0f.shared.v1.NodeR\x06parent\x12/\n" +
	"\tquestions\x18\x06 \x03(\v2\x11.shared.v1.PromptR\tquestionsBDZBgithub.com/studyguides-com/study-guides-api/api/v1/shared;sharedv1b\x06proto3"

var (
	file_v1_shared_node_proto_rawDescOnce sync.Once
	file_v1_shared_node_proto_rawDescData []byte
)

func file_v1_shared_node_proto_rawDescGZIP() []byte {
	file_v1_shared_node_proto_rawDescOnce.Do(func() {
		file_v1_shared_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_shared_node_proto_rawDesc), len(file_v1_shared_node_proto_rawDesc)))
	})
	return file_v1_shared_node_proto_rawDescData
}

var file_v1_shared_node_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_shared_node_proto_goTypes = []any{
	(*Node)(nil),   // 0: shared.v1.Node
	(*Prompt)(nil), // 1: shared.v1.Prompt
}
var file_v1_shared_node_proto_depIdxs = []int32{
	0, // 0: shared.v1.Node.parent:type_name -> shared.v1.Node
	1, // 1: shared.v1.Node.questions:type_name -> shared.v1.Prompt
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_shared_node_proto_init() }
func file_v1_shared_node_proto_init() {
	if File_v1_shared_node_proto != nil {
		return
	}
	file_v1_shared_prompt_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_shared_node_proto_rawDesc), len(file_v1_shared_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_shared_node_proto_goTypes,
		DependencyIndexes: file_v1_shared_node_proto_depIdxs,
		MessageInfos:      file_v1_shared_node_proto_msgTypes,
	}.Build()
	File_v1_shared_node_proto = out.File
	file_v1_shared_node_proto_goTypes = nil
	file_v1_shared_node_proto_depIdxs = nil
}
