// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/shared/parsertype.proto

package sharedv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ParserType represents different types of parsers
type ParserType int32

const (
	// Default value, should not be used
	ParserType_PARSER_TYPE_UNSPECIFIED ParserType = 0
	// Parser types
	ParserType_PARSER_TYPE_COLLEGES       ParserType = 1
	ParserType_PARSER_TYPE_CERTIFICATIONS ParserType = 2
	ParserType_PARSER_TYPE_ENTRANCE_EXAMS ParserType = 3
	ParserType_PARSER_TYPE_AP_EXAMS       ParserType = 4
	ParserType_PARSER_TYPE_DOD            ParserType = 5
)

// Enum value maps for ParserType.
var (
	ParserType_name = map[int32]string{
		0: "PARSER_TYPE_UNSPECIFIED",
		1: "PARSER_TYPE_COLLEGES",
		2: "PARSER_TYPE_CERTIFICATIONS",
		3: "PARSER_TYPE_ENTRANCE_EXAMS",
		4: "PARSER_TYPE_AP_EXAMS",
		5: "PARSER_TYPE_DOD",
	}
	ParserType_value = map[string]int32{
		"PARSER_TYPE_UNSPECIFIED":    0,
		"PARSER_TYPE_COLLEGES":       1,
		"PARSER_TYPE_CERTIFICATIONS": 2,
		"PARSER_TYPE_ENTRANCE_EXAMS": 3,
		"PARSER_TYPE_AP_EXAMS":       4,
		"PARSER_TYPE_DOD":            5,
	}
)

func (x ParserType) Enum() *ParserType {
	p := new(ParserType)
	*p = x
	return p
}

func (x ParserType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParserType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_shared_parsertype_proto_enumTypes[0].Descriptor()
}

func (ParserType) Type() protoreflect.EnumType {
	return &file_v1_shared_parsertype_proto_enumTypes[0]
}

func (x ParserType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParserType.Descriptor instead.
func (ParserType) EnumDescriptor() ([]byte, []int) {
	return file_v1_shared_parsertype_proto_rawDescGZIP(), []int{0}
}

var File_v1_shared_parsertype_proto protoreflect.FileDescriptor

const file_v1_shared_parsertype_proto_rawDesc = "" +
	"\n" +
	"\x1av1/shared/parsertype.proto\x12\tshared.v1*\xb2\x01\n" +
	"\n" +
	"ParserType\x12\x1b\n" +
	"\x17PARSER_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PARSER_TYPE_COLLEGES\x10\x01\x12\x1e\n" +
	"\x1aPARSER_TYPE_CERTIFICATIONS\x10\x02\x12\x1e\n" +
	"\x1aPARSER_TYPE_ENTRANCE_EXAMS\x10\x03\x12\x18\n" +
	"\x14PARSER_TYPE_AP_EXAMS\x10\x04\x12\x13\n" +
	"\x0fPARSER_TYPE_DOD\x10\x05BDZBgithub.com/studyguides-com/study-guides-api/api/v1/shared;sharedv1b\x06proto3"

var (
	file_v1_shared_parsertype_proto_rawDescOnce sync.Once
	file_v1_shared_parsertype_proto_rawDescData []byte
)

func file_v1_shared_parsertype_proto_rawDescGZIP() []byte {
	file_v1_shared_parsertype_proto_rawDescOnce.Do(func() {
		file_v1_shared_parsertype_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_shared_parsertype_proto_rawDesc), len(file_v1_shared_parsertype_proto_rawDesc)))
	})
	return file_v1_shared_parsertype_proto_rawDescData
}

var file_v1_shared_parsertype_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_shared_parsertype_proto_goTypes = []any{
	(ParserType)(0), // 0: shared.v1.ParserType
}
var file_v1_shared_parsertype_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_shared_parsertype_proto_init() }
func file_v1_shared_parsertype_proto_init() {
	if File_v1_shared_parsertype_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_shared_parsertype_proto_rawDesc), len(file_v1_shared_parsertype_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_shared_parsertype_proto_goTypes,
		DependencyIndexes: file_v1_shared_parsertype_proto_depIdxs,
		EnumInfos:         file_v1_shared_parsertype_proto_enumTypes,
	}.Build()
	File_v1_shared_parsertype_proto = out.File
	file_v1_shared_parsertype_proto_goTypes = nil
	file_v1_shared_parsertype_proto_depIdxs = nil
}
