// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/shared/passage.proto

package sharedv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Passage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Hash          string                 `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	TagId         string                 `protobuf:"bytes,5,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Passage) Reset() {
	*x = Passage{}
	mi := &file_v1_shared_passage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Passage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Passage) ProtoMessage() {}

func (x *Passage) ProtoReflect() protoreflect.Message {
	mi := &file_v1_shared_passage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Passage.ProtoReflect.Descriptor instead.
func (*Passage) Descriptor() ([]byte, []int) {
	return file_v1_shared_passage_proto_rawDescGZIP(), []int{0}
}

func (x *Passage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Passage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Passage) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Passage) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Passage) GetTagId() string {
	if x != nil {
		return x.TagId
	}
	return ""
}

func (x *Passage) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Passage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Passage) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_v1_shared_passage_proto protoreflect.FileDescriptor

const file_v1_shared_passage_proto_rawDesc = "" +
	"\n" +
	"\x17v1/shared/passage.proto\x12\tshared.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18v1/shared/metadata.proto\"\x95\x02\n" +
	"\aPassage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\tR\x04hash\x12\x15\n" +
	"\x06tag_id\x18\x05 \x01(\tR\x05tagId\x12/\n" +
	"\bmetadata\x18\x06 \x01(\v2\x13.shared.v1.MetadataR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtBDZBgithub.com/studyguides-com/study-guides-api/api/v1/shared;sharedv1b\x06proto3"

var (
	file_v1_shared_passage_proto_rawDescOnce sync.Once
	file_v1_shared_passage_proto_rawDescData []byte
)

func file_v1_shared_passage_proto_rawDescGZIP() []byte {
	file_v1_shared_passage_proto_rawDescOnce.Do(func() {
		file_v1_shared_passage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_shared_passage_proto_rawDesc), len(file_v1_shared_passage_proto_rawDesc)))
	})
	return file_v1_shared_passage_proto_rawDescData
}

var file_v1_shared_passage_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_shared_passage_proto_goTypes = []any{
	(*Passage)(nil),               // 0: shared.v1.Passage
	(*Metadata)(nil),              // 1: shared.v1.Metadata
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_v1_shared_passage_proto_depIdxs = []int32{
	1, // 0: shared.v1.Passage.metadata:type_name -> shared.v1.Metadata
	2, // 1: shared.v1.Passage.created_at:type_name -> google.protobuf.Timestamp
	2, // 2: shared.v1.Passage.updated_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_shared_passage_proto_init() }
func file_v1_shared_passage_proto_init() {
	if File_v1_shared_passage_proto != nil {
		return
	}
	file_v1_shared_metadata_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_shared_passage_proto_rawDesc), len(file_v1_shared_passage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_shared_passage_proto_goTypes,
		DependencyIndexes: file_v1_shared_passage_proto_depIdxs,
		MessageInfos:      file_v1_shared_passage_proto_msgTypes,
	}.Build()
	File_v1_shared_passage_proto = out.File
	file_v1_shared_passage_proto_goTypes = nil
	file_v1_shared_passage_proto_depIdxs = nil
}
