// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/shared/questiontag.proto

package sharedv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuestionTag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	TagId         string                 `protobuf:"bytes,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionTag) Reset() {
	*x = QuestionTag{}
	mi := &file_v1_shared_questiontag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionTag) ProtoMessage() {}

func (x *QuestionTag) ProtoReflect() protoreflect.Message {
	mi := &file_v1_shared_questiontag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionTag.ProtoReflect.Descriptor instead.
func (*QuestionTag) Descriptor() ([]byte, []int) {
	return file_v1_shared_questiontag_proto_rawDescGZIP(), []int{0}
}

func (x *QuestionTag) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *QuestionTag) GetTagId() string {
	if x != nil {
		return x.TagId
	}
	return ""
}

func (x *QuestionTag) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_v1_shared_questiontag_proto protoreflect.FileDescriptor

const file_v1_shared_questiontag_proto_rawDesc = "" +
	"\n" +
	"\x1bv1/shared/questiontag.proto\x12\tshared.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x01\n" +
	"\vQuestionTag\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12\x15\n" +
	"\x06tag_id\x18\x02 \x01(\tR\x05tagId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtBDZBgithub.com/studyguides-com/study-guides-api/api/v1/shared;sharedv1b\x06proto3"

var (
	file_v1_shared_questiontag_proto_rawDescOnce sync.Once
	file_v1_shared_questiontag_proto_rawDescData []byte
)

func file_v1_shared_questiontag_proto_rawDescGZIP() []byte {
	file_v1_shared_questiontag_proto_rawDescOnce.Do(func() {
		file_v1_shared_questiontag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_shared_questiontag_proto_rawDesc), len(file_v1_shared_questiontag_proto_rawDesc)))
	})
	return file_v1_shared_questiontag_proto_rawDescData
}

var file_v1_shared_questiontag_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_shared_questiontag_proto_goTypes = []any{
	(*QuestionTag)(nil),           // 0: shared.v1.QuestionTag
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_v1_shared_questiontag_proto_depIdxs = []int32{
	1, // 0: shared.v1.QuestionTag.created_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_shared_questiontag_proto_init() }
func file_v1_shared_questiontag_proto_init() {
	if File_v1_shared_questiontag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_shared_questiontag_proto_rawDesc), len(file_v1_shared_questiontag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_shared_questiontag_proto_goTypes,
		DependencyIndexes: file_v1_shared_questiontag_proto_depIdxs,
		MessageInfos:      file_v1_shared_questiontag_proto_msgTypes,
	}.Build()
	File_v1_shared_questiontag_proto = out.File
	file_v1_shared_questiontag_proto_goTypes = nil
	file_v1_shared_questiontag_proto_depIdxs = nil
}
