// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/shared/question.proto

package sharedv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Question represents a question in the system
type Question struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BatchId         string                 `protobuf:"bytes,2,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	QuestionText    string                 `protobuf:"bytes,3,opt,name=question_text,json=questionText,proto3" json:"question_text,omitempty"`
	AnswerText      string                 `protobuf:"bytes,4,opt,name=answer_text,json=answerText,proto3" json:"answer_text,omitempty"`
	Hash            string                 `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	LearnMore       string                 `protobuf:"bytes,6,opt,name=learn_more,json=learnMore,proto3" json:"learn_more,omitempty"`
	Distractors     []string               `protobuf:"bytes,7,rep,name=distractors,proto3" json:"distractors,omitempty"`
	VideoUrl        string                 `protobuf:"bytes,8,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	ImageUrl        string                 `protobuf:"bytes,9,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Version         int32                  `protobuf:"varint,10,opt,name=version,proto3" json:"version,omitempty"`
	Public          bool                   `protobuf:"varint,11,opt,name=public,proto3" json:"public,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,12,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CorrectCount    int32                  `protobuf:"varint,15,opt,name=correct_count,json=correctCount,proto3" json:"correct_count,omitempty"`
	DifficultyRatio float64                `protobuf:"fixed64,16,opt,name=difficulty_ratio,json=difficultyRatio,proto3" json:"difficulty_ratio,omitempty"`
	IncorrectCount  int32                  `protobuf:"varint,17,opt,name=incorrect_count,json=incorrectCount,proto3" json:"incorrect_count,omitempty"`
	OwnerId         string                 `protobuf:"bytes,18,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	PassageId       string                 `protobuf:"bytes,19,opt,name=passage_id,json=passageId,proto3" json:"passage_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_v1_shared_question_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_v1_shared_question_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_v1_shared_question_proto_rawDescGZIP(), []int{0}
}

func (x *Question) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Question) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *Question) GetQuestionText() string {
	if x != nil {
		return x.QuestionText
	}
	return ""
}

func (x *Question) GetAnswerText() string {
	if x != nil {
		return x.AnswerText
	}
	return ""
}

func (x *Question) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Question) GetLearnMore() string {
	if x != nil {
		return x.LearnMore
	}
	return ""
}

func (x *Question) GetDistractors() []string {
	if x != nil {
		return x.Distractors
	}
	return nil
}

func (x *Question) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *Question) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Question) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Question) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

func (x *Question) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Question) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Question) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Question) GetCorrectCount() int32 {
	if x != nil {
		return x.CorrectCount
	}
	return 0
}

func (x *Question) GetDifficultyRatio() float64 {
	if x != nil {
		return x.DifficultyRatio
	}
	return 0
}

func (x *Question) GetIncorrectCount() int32 {
	if x != nil {
		return x.IncorrectCount
	}
	return 0
}

func (x *Question) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Question) GetPassageId() string {
	if x != nil {
		return x.PassageId
	}
	return ""
}

var File_v1_shared_question_proto protoreflect.FileDescriptor

const file_v1_shared_question_proto_rawDesc = "" +
	"\n" +
	"\x18v1/shared/question.proto\x12\tshared.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe1\x05\n" +
	"\bQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bbatch_id\x18\x02 \x01(\tR\abatchId\x12#\n" +
	"\rquestion_text\x18\x03 \x01(\tR\fquestionText\x12\x1f\n" +
	"\vanswer_text\x18\x04 \x01(\tR\n" +
	"answerText\x12\x12\n" +
	"\x04hash\x18\x05 \x01(\tR\x04hash\x12\x1d\n" +
	"\n" +
	"learn_more\x18\x06 \x01(\tR\tlearnMore\x12 \n" +
	"\vdistractors\x18\a \x03(\tR\vdistractors\x12\x1b\n" +
	"\tvideo_url\x18\b \x01(\tR\bvideoUrl\x12\x1b\n" +
	"\timage_url\x18\t \x01(\tR\bimageUrl\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\x05R\aversion\x12\x16\n" +
	"\x06public\x18\v \x01(\bR\x06public\x12=\n" +
	"\bmetadata\x18\f \x03(\v2!.shared.v1.Question.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12#\n" +
	"\rcorrect_count\x18\x0f \x01(\x05R\fcorrectCount\x12)\n" +
	"\x10difficulty_ratio\x18\x10 \x01(\x01R\x0fdifficultyRatio\x12'\n" +
	"\x0fincorrect_count\x18\x11 \x01(\x05R\x0eincorrectCount\x12\x19\n" +
	"\bowner_id\x18\x12 \x01(\tR\aownerId\x12\x1d\n" +
	"\n" +
	"passage_id\x18\x13 \x01(\tR\tpassageId\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01BDZBgithub.com/studyguides-com/study-guides-api/api/v1/shared;sharedv1b\x06proto3"

var (
	file_v1_shared_question_proto_rawDescOnce sync.Once
	file_v1_shared_question_proto_rawDescData []byte
)

func file_v1_shared_question_proto_rawDescGZIP() []byte {
	file_v1_shared_question_proto_rawDescOnce.Do(func() {
		file_v1_shared_question_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_shared_question_proto_rawDesc), len(file_v1_shared_question_proto_rawDesc)))
	})
	return file_v1_shared_question_proto_rawDescData
}

var file_v1_shared_question_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_shared_question_proto_goTypes = []any{
	(*Question)(nil),              // 0: shared.v1.Question
	nil,                           // 1: shared.v1.Question.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_v1_shared_question_proto_depIdxs = []int32{
	1, // 0: shared.v1.Question.metadata:type_name -> shared.v1.Question.MetadataEntry
	2, // 1: shared.v1.Question.created_at:type_name -> google.protobuf.Timestamp
	2, // 2: shared.v1.Question.updated_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_shared_question_proto_init() }
func file_v1_shared_question_proto_init() {
	if File_v1_shared_question_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_shared_question_proto_rawDesc), len(file_v1_shared_question_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_shared_question_proto_goTypes,
		DependencyIndexes: file_v1_shared_question_proto_depIdxs,
		MessageInfos:      file_v1_shared_question_proto_msgTypes,
	}.Build()
	File_v1_shared_question_proto = out.File
	file_v1_shared_question_proto_goTypes = nil
	file_v1_shared_question_proto_depIdxs = nil
}
