// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/shared/reporttype.proto

package sharedv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReportType int32

const (
	ReportType_REPORT_TYPE_SPAM          ReportType = 0
	ReportType_REPORT_TYPE_INAPPROPRIATE ReportType = 1
	ReportType_REPORT_TYPE_INCORRECT     ReportType = 2
	ReportType_REPORT_TYPE_OTHER         ReportType = 3
)

// Enum value maps for ReportType.
var (
	ReportType_name = map[int32]string{
		0: "REPORT_TYPE_SPAM",
		1: "REPORT_TYPE_INAPPROPRIATE",
		2: "REPORT_TYPE_INCORRECT",
		3: "REPORT_TYPE_OTHER",
	}
	ReportType_value = map[string]int32{
		"REPORT_TYPE_SPAM":          0,
		"REPORT_TYPE_INAPPROPRIATE": 1,
		"REPORT_TYPE_INCORRECT":     2,
		"REPORT_TYPE_OTHER":         3,
	}
)

func (x ReportType) Enum() *ReportType {
	p := new(ReportType)
	*p = x
	return p
}

func (x ReportType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReportType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_shared_reporttype_proto_enumTypes[0].Descriptor()
}

func (ReportType) Type() protoreflect.EnumType {
	return &file_v1_shared_reporttype_proto_enumTypes[0]
}

func (x ReportType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReportType.Descriptor instead.
func (ReportType) EnumDescriptor() ([]byte, []int) {
	return file_v1_shared_reporttype_proto_rawDescGZIP(), []int{0}
}

var File_v1_shared_reporttype_proto protoreflect.FileDescriptor

const file_v1_shared_reporttype_proto_rawDesc = "" +
	"\n" +
	"\x1av1/shared/reporttype.proto\x12\tshared.v1*s\n" +
	"\n" +
	"ReportType\x12\x14\n" +
	"\x10REPORT_TYPE_SPAM\x10\x00\x12\x1d\n" +
	"\x19REPORT_TYPE_INAPPROPRIATE\x10\x01\x12\x19\n" +
	"\x15REPORT_TYPE_INCORRECT\x10\x02\x12\x15\n" +
	"\x11REPORT_TYPE_OTHER\x10\x03BDZBgithub.com/studyguides-com/study-guides-api/api/v1/shared;sharedv1b\x06proto3"

var (
	file_v1_shared_reporttype_proto_rawDescOnce sync.Once
	file_v1_shared_reporttype_proto_rawDescData []byte
)

func file_v1_shared_reporttype_proto_rawDescGZIP() []byte {
	file_v1_shared_reporttype_proto_rawDescOnce.Do(func() {
		file_v1_shared_reporttype_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_shared_reporttype_proto_rawDesc), len(file_v1_shared_reporttype_proto_rawDesc)))
	})
	return file_v1_shared_reporttype_proto_rawDescData
}

var file_v1_shared_reporttype_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_shared_reporttype_proto_goTypes = []any{
	(ReportType)(0), // 0: shared.v1.ReportType
}
var file_v1_shared_reporttype_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_shared_reporttype_proto_init() }
func file_v1_shared_reporttype_proto_init() {
	if File_v1_shared_reporttype_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_shared_reporttype_proto_rawDesc), len(file_v1_shared_reporttype_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_shared_reporttype_proto_goTypes,
		DependencyIndexes: file_v1_shared_reporttype_proto_depIdxs,
		EnumInfos:         file_v1_shared_reporttype_proto_enumTypes,
	}.Build()
	File_v1_shared_reporttype_proto = out.File
	file_v1_shared_reporttype_proto_goTypes = nil
	file_v1_shared_reporttype_proto_depIdxs = nil
}
