// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/shared/section.proto

package sharedv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SectionData struct {
	state              protoimpl.MessageState  `protogen:"open.v1"`
	Title              string                  `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	ContentRating      ContentRating           `protobuf:"varint,2,opt,name=content_rating,json=contentRating,proto3,enum=shared.v1.ContentRating" json:"content_rating,omitempty"`
	ContentDescriptors []ContentDescriptorType `protobuf:"varint,3,rep,packed,name=content_descriptors,json=contentDescriptors,proto3,enum=shared.v1.ContentDescriptorType" json:"content_descriptors,omitempty"`
	MetaTags           []string                `protobuf:"bytes,4,rep,name=meta_tags,json=metaTags,proto3" json:"meta_tags,omitempty"`
	Prompts            []*PromptData           `protobuf:"bytes,5,rep,name=prompts,proto3" json:"prompts,omitempty"`
	Passages           []*PassageData          `protobuf:"bytes,6,rep,name=passages,proto3" json:"passages,omitempty"`
	Ancestor           *Ancestor               `protobuf:"bytes,7,opt,name=ancestor,proto3" json:"ancestor,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SectionData) Reset() {
	*x = SectionData{}
	mi := &file_v1_shared_section_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SectionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SectionData) ProtoMessage() {}

func (x *SectionData) ProtoReflect() protoreflect.Message {
	mi := &file_v1_shared_section_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SectionData.ProtoReflect.Descriptor instead.
func (*SectionData) Descriptor() ([]byte, []int) {
	return file_v1_shared_section_proto_rawDescGZIP(), []int{0}
}

func (x *SectionData) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SectionData) GetContentRating() ContentRating {
	if x != nil {
		return x.ContentRating
	}
	return ContentRating_Unspecified
}

func (x *SectionData) GetContentDescriptors() []ContentDescriptorType {
	if x != nil {
		return x.ContentDescriptors
	}
	return nil
}

func (x *SectionData) GetMetaTags() []string {
	if x != nil {
		return x.MetaTags
	}
	return nil
}

func (x *SectionData) GetPrompts() []*PromptData {
	if x != nil {
		return x.Prompts
	}
	return nil
}

func (x *SectionData) GetPassages() []*PassageData {
	if x != nil {
		return x.Passages
	}
	return nil
}

func (x *SectionData) GetAncestor() *Ancestor {
	if x != nil {
		return x.Ancestor
	}
	return nil
}

var File_v1_shared_section_proto protoreflect.FileDescriptor

const file_v1_shared_section_proto_rawDesc = "" +
	"\n" +
	"\x17v1/shared/section.proto\x12\tshared.v1\x1a\x16v1/shared/prompt.proto\x1a\x17v1/shared/passage.proto\x1a\x18v1/shared/ancestor.proto\x1a\x1dv1/shared/contentrating.proto\x1a%v1/shared/contentdescriptortype.proto\"\xea\x02\n" +
	"\vSectionData\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12?\n" +
	"\x0econtent_rating\x18\x02 \x01(\x0e2\x18.shared.v1.ContentRatingR\rcontentRating\x12Q\n" +
	"\x13content_descriptors\x18\x03 \x03(\x0e2 .shared.v1.ContentDescriptorTypeR\x12contentDescriptors\x12\x1b\n" +
	"\tmeta_tags\x18\x04 \x03(\tR\bmetaTags\x12/\n" +
	"\aprompts\x18\x05 \x03(\v2\x15.shared.v1.PromptDataR\aprompts\x122\n" +
	"\bpassages\x18\x06 \x03(\v2\x16.shared.v1.PassageDataR\bpassages\x12/\n" +
	"\bancestor\x18\a \x01(\v2\x13.shared.v1.AncestorR\bancestorBDZBgithub.com/studyguides-com/study-guides-api/api/v1/shared;sharedv1b\x06proto3"

var (
	file_v1_shared_section_proto_rawDescOnce sync.Once
	file_v1_shared_section_proto_rawDescData []byte
)

func file_v1_shared_section_proto_rawDescGZIP() []byte {
	file_v1_shared_section_proto_rawDescOnce.Do(func() {
		file_v1_shared_section_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_shared_section_proto_rawDesc), len(file_v1_shared_section_proto_rawDesc)))
	})
	return file_v1_shared_section_proto_rawDescData
}

var file_v1_shared_section_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_shared_section_proto_goTypes = []any{
	(*SectionData)(nil),        // 0: shared.v1.SectionData
	(ContentRating)(0),         // 1: shared.v1.ContentRating
	(ContentDescriptorType)(0), // 2: shared.v1.ContentDescriptorType
	(*PromptData)(nil),         // 3: shared.v1.PromptData
	(*PassageData)(nil),        // 4: shared.v1.PassageData
	(*Ancestor)(nil),           // 5: shared.v1.Ancestor
}
var file_v1_shared_section_proto_depIdxs = []int32{
	1, // 0: shared.v1.SectionData.content_rating:type_name -> shared.v1.ContentRating
	2, // 1: shared.v1.SectionData.content_descriptors:type_name -> shared.v1.ContentDescriptorType
	3, // 2: shared.v1.SectionData.prompts:type_name -> shared.v1.PromptData
	4, // 3: shared.v1.SectionData.passages:type_name -> shared.v1.PassageData
	5, // 4: shared.v1.SectionData.ancestor:type_name -> shared.v1.Ancestor
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_v1_shared_section_proto_init() }
func file_v1_shared_section_proto_init() {
	if File_v1_shared_section_proto != nil {
		return
	}
	file_v1_shared_prompt_proto_init()
	file_v1_shared_passage_proto_init()
	file_v1_shared_ancestor_proto_init()
	file_v1_shared_contentrating_proto_init()
	file_v1_shared_contentdescriptortype_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_shared_section_proto_rawDesc), len(file_v1_shared_section_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_shared_section_proto_goTypes,
		DependencyIndexes: file_v1_shared_section_proto_depIdxs,
		MessageInfos:      file_v1_shared_section_proto_msgTypes,
	}.Build()
	File_v1_shared_section_proto = out.File
	file_v1_shared_section_proto_goTypes = nil
	file_v1_shared_section_proto_depIdxs = nil
}
