// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/shared/studymethod.proto

package sharedv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StudyMethod int32

const (
	StudyMethod_STUDY_METHOD_STUDY_GUIDE     StudyMethod = 0
	StudyMethod_STUDY_METHOD_FLASHCARDS      StudyMethod = 1
	StudyMethod_STUDY_METHOD_MULTIPLE_CHOICE StudyMethod = 2
	StudyMethod_STUDY_METHOD_SURVIVAL        StudyMethod = 3
	StudyMethod_STUDY_METHOD_MATCH_GAME      StudyMethod = 4
	StudyMethod_STUDY_METHOD_TEST            StudyMethod = 6
	StudyMethod_STUDY_METHOD_QUIZ            StudyMethod = 7
	StudyMethod_STUDY_METHOD_NONE            StudyMethod = 8
)

// Enum value maps for StudyMethod.
var (
	StudyMethod_name = map[int32]string{
		0: "STUDY_METHOD_STUDY_GUIDE",
		1: "STUDY_METHOD_FLASHCARDS",
		2: "STUDY_METHOD_MULTIPLE_CHOICE",
		3: "STUDY_METHOD_SURVIVAL",
		4: "STUDY_METHOD_MATCH_GAME",
		6: "STUDY_METHOD_TEST",
		7: "STUDY_METHOD_QUIZ",
		8: "STUDY_METHOD_NONE",
	}
	StudyMethod_value = map[string]int32{
		"STUDY_METHOD_STUDY_GUIDE":     0,
		"STUDY_METHOD_FLASHCARDS":      1,
		"STUDY_METHOD_MULTIPLE_CHOICE": 2,
		"STUDY_METHOD_SURVIVAL":        3,
		"STUDY_METHOD_MATCH_GAME":      4,
		"STUDY_METHOD_TEST":            6,
		"STUDY_METHOD_QUIZ":            7,
		"STUDY_METHOD_NONE":            8,
	}
)

func (x StudyMethod) Enum() *StudyMethod {
	p := new(StudyMethod)
	*p = x
	return p
}

func (x StudyMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StudyMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_shared_studymethod_proto_enumTypes[0].Descriptor()
}

func (StudyMethod) Type() protoreflect.EnumType {
	return &file_v1_shared_studymethod_proto_enumTypes[0]
}

func (x StudyMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StudyMethod.Descriptor instead.
func (StudyMethod) EnumDescriptor() ([]byte, []int) {
	return file_v1_shared_studymethod_proto_rawDescGZIP(), []int{0}
}

var File_v1_shared_studymethod_proto protoreflect.FileDescriptor

const file_v1_shared_studymethod_proto_rawDesc = "" +
	"\n" +
	"\x1bv1/shared/studymethod.proto\x12\tshared.v1*\xe7\x01\n" +
	"\vStudyMethod\x12\x1c\n" +
	"\x18STUDY_METHOD_STUDY_GUIDE\x10\x00\x12\x1b\n" +
	"\x17STUDY_METHOD_FLASHCARDS\x10\x01\x12 \n" +
	"\x1cSTUDY_METHOD_MULTIPLE_CHOICE\x10\x02\x12\x19\n" +
	"\x15STUDY_METHOD_SURVIVAL\x10\x03\x12\x1b\n" +
	"\x17STUDY_METHOD_MATCH_GAME\x10\x04\x12\x15\n" +
	"\x11STUDY_METHOD_TEST\x10\x06\x12\x15\n" +
	"\x11STUDY_METHOD_QUIZ\x10\a\x12\x15\n" +
	"\x11STUDY_METHOD_NONE\x10\bBDZBgithub.com/studyguides-com/study-guides-api/api/v1/shared;sharedv1b\x06proto3"

var (
	file_v1_shared_studymethod_proto_rawDescOnce sync.Once
	file_v1_shared_studymethod_proto_rawDescData []byte
)

func file_v1_shared_studymethod_proto_rawDescGZIP() []byte {
	file_v1_shared_studymethod_proto_rawDescOnce.Do(func() {
		file_v1_shared_studymethod_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_shared_studymethod_proto_rawDesc), len(file_v1_shared_studymethod_proto_rawDesc)))
	})
	return file_v1_shared_studymethod_proto_rawDescData
}

var file_v1_shared_studymethod_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_shared_studymethod_proto_goTypes = []any{
	(StudyMethod)(0), // 0: shared.v1.StudyMethod
}
var file_v1_shared_studymethod_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_shared_studymethod_proto_init() }
func file_v1_shared_studymethod_proto_init() {
	if File_v1_shared_studymethod_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_shared_studymethod_proto_rawDesc), len(file_v1_shared_studymethod_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_shared_studymethod_proto_goTypes,
		DependencyIndexes: file_v1_shared_studymethod_proto_depIdxs,
		EnumInfos:         file_v1_shared_studymethod_proto_enumTypes,
	}.Build()
	File_v1_shared_studymethod_proto = out.File
	file_v1_shared_studymethod_proto_goTypes = nil
	file_v1_shared_studymethod_proto_depIdxs = nil
}
