// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/shared/taginfo.proto

package sharedv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TagInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          TagType                `protobuf:"varint,3,opt,name=type,proto3,enum=shared.v1.TagType" json:"type,omitempty"`
	ParentTagId   string                 `protobuf:"bytes,4,opt,name=parent_tag_id,json=parentTagId,proto3" json:"parent_tag_id,omitempty"`
	HasQuestions  bool                   `protobuf:"varint,5,opt,name=has_questions,json=hasQuestions,proto3" json:"has_questions,omitempty"`
	HasChildren   bool                   `protobuf:"varint,6,opt,name=has_children,json=hasChildren,proto3" json:"has_children,omitempty"`
	Private       bool                   `protobuf:"varint,7,opt,name=private,proto3" json:"private,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagInfo) Reset() {
	*x = TagInfo{}
	mi := &file_v1_shared_taginfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagInfo) ProtoMessage() {}

func (x *TagInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v1_shared_taginfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagInfo.ProtoReflect.Descriptor instead.
func (*TagInfo) Descriptor() ([]byte, []int) {
	return file_v1_shared_taginfo_proto_rawDescGZIP(), []int{0}
}

func (x *TagInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TagInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagInfo) GetType() TagType {
	if x != nil {
		return x.Type
	}
	return TagType_Category
}

func (x *TagInfo) GetParentTagId() string {
	if x != nil {
		return x.ParentTagId
	}
	return ""
}

func (x *TagInfo) GetHasQuestions() bool {
	if x != nil {
		return x.HasQuestions
	}
	return false
}

func (x *TagInfo) GetHasChildren() bool {
	if x != nil {
		return x.HasChildren
	}
	return false
}

func (x *TagInfo) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

var File_v1_shared_taginfo_proto protoreflect.FileDescriptor

const file_v1_shared_taginfo_proto_rawDesc = "" +
	"\n" +
	"\x17v1/shared/taginfo.proto\x12\tshared.v1\x1a\x17v1/shared/tagtype.proto\"\xdb\x01\n" +
	"\aTagInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\x04type\x18\x03 \x01(\x0e2\x12.shared.v1.TagTypeR\x04type\x12\"\n" +
	"\rparent_tag_id\x18\x04 \x01(\tR\vparentTagId\x12#\n" +
	"\rhas_questions\x18\x05 \x01(\bR\fhasQuestions\x12!\n" +
	"\fhas_children\x18\x06 \x01(\bR\vhasChildren\x12\x18\n" +
	"\aprivate\x18\a \x01(\bR\aprivateBDZBgithub.com/studyguides-com/study-guides-api/api/v1/shared;sharedv1b\x06proto3"

var (
	file_v1_shared_taginfo_proto_rawDescOnce sync.Once
	file_v1_shared_taginfo_proto_rawDescData []byte
)

func file_v1_shared_taginfo_proto_rawDescGZIP() []byte {
	file_v1_shared_taginfo_proto_rawDescOnce.Do(func() {
		file_v1_shared_taginfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_shared_taginfo_proto_rawDesc), len(file_v1_shared_taginfo_proto_rawDesc)))
	})
	return file_v1_shared_taginfo_proto_rawDescData
}

var file_v1_shared_taginfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_shared_taginfo_proto_goTypes = []any{
	(*TagInfo)(nil), // 0: shared.v1.TagInfo
	(TagType)(0),    // 1: shared.v1.TagType
}
var file_v1_shared_taginfo_proto_depIdxs = []int32{
	1, // 0: shared.v1.TagInfo.type:type_name -> shared.v1.TagType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_shared_taginfo_proto_init() }
func file_v1_shared_taginfo_proto_init() {
	if File_v1_shared_taginfo_proto != nil {
		return
	}
	file_v1_shared_tagtype_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_shared_taginfo_proto_rawDesc), len(file_v1_shared_taginfo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_shared_taginfo_proto_goTypes,
		DependencyIndexes: file_v1_shared_taginfo_proto_depIdxs,
		MessageInfos:      file_v1_shared_taginfo_proto_msgTypes,
	}.Build()
	File_v1_shared_taginfo_proto = out.File
	file_v1_shared_taginfo_proto_goTypes = nil
	file_v1_shared_taginfo_proto_depIdxs = nil
}
