// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/shared/tagindexresult.proto

package sharedv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TagIndexResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           *Tag                   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	TagInfos      []*TagInfo             `protobuf:"bytes,2,rep,name=tag_infos,json=tagInfos,proto3" json:"tag_infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagIndexResult) Reset() {
	*x = TagIndexResult{}
	mi := &file_v1_shared_tagindexresult_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagIndexResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagIndexResult) ProtoMessage() {}

func (x *TagIndexResult) ProtoReflect() protoreflect.Message {
	mi := &file_v1_shared_tagindexresult_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagIndexResult.ProtoReflect.Descriptor instead.
func (*TagIndexResult) Descriptor() ([]byte, []int) {
	return file_v1_shared_tagindexresult_proto_rawDescGZIP(), []int{0}
}

func (x *TagIndexResult) GetTag() *Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *TagIndexResult) GetTagInfos() []*TagInfo {
	if x != nil {
		return x.TagInfos
	}
	return nil
}

var File_v1_shared_tagindexresult_proto protoreflect.FileDescriptor

const file_v1_shared_tagindexresult_proto_rawDesc = "" +
	"\n" +
	"\x1ev1/shared/tagindexresult.proto\x12\tshared.v1\x1a\x13v1/shared/tag.proto\x1a\x17v1/shared/taginfo.proto\"c\n" +
	"\x0eTagIndexResult\x12 \n" +
	"\x03tag\x18\x01 \x01(\v2\x0e.shared.v1.TagR\x03tag\x12/\n" +
	"\ttag_infos\x18\x02 \x03(\v2\x12.shared.v1.TagInfoR\btagInfosBDZBgithub.com/studyguides-com/study-guides-api/api/v1/shared;sharedv1b\x06proto3"

var (
	file_v1_shared_tagindexresult_proto_rawDescOnce sync.Once
	file_v1_shared_tagindexresult_proto_rawDescData []byte
)

func file_v1_shared_tagindexresult_proto_rawDescGZIP() []byte {
	file_v1_shared_tagindexresult_proto_rawDescOnce.Do(func() {
		file_v1_shared_tagindexresult_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_shared_tagindexresult_proto_rawDesc), len(file_v1_shared_tagindexresult_proto_rawDesc)))
	})
	return file_v1_shared_tagindexresult_proto_rawDescData
}

var file_v1_shared_tagindexresult_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_shared_tagindexresult_proto_goTypes = []any{
	(*TagIndexResult)(nil), // 0: shared.v1.TagIndexResult
	(*Tag)(nil),            // 1: shared.v1.Tag
	(*TagInfo)(nil),        // 2: shared.v1.TagInfo
}
var file_v1_shared_tagindexresult_proto_depIdxs = []int32{
	1, // 0: shared.v1.TagIndexResult.tag:type_name -> shared.v1.Tag
	2, // 1: shared.v1.TagIndexResult.tag_infos:type_name -> shared.v1.TagInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_shared_tagindexresult_proto_init() }
func file_v1_shared_tagindexresult_proto_init() {
	if File_v1_shared_tagindexresult_proto != nil {
		return
	}
	file_v1_shared_tag_proto_init()
	file_v1_shared_taginfo_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_shared_tagindexresult_proto_rawDesc), len(file_v1_shared_tagindexresult_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_shared_tagindexresult_proto_goTypes,
		DependencyIndexes: file_v1_shared_tagindexresult_proto_depIdxs,
		MessageInfos:      file_v1_shared_tagindexresult_proto_msgTypes,
	}.Build()
	File_v1_shared_tagindexresult_proto = out.File
	file_v1_shared_tagindexresult_proto_goTypes = nil
	file_v1_shared_tagindexresult_proto_depIdxs = nil
}
