// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/shared/tagnode.proto

package sharedv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TagNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagRow        *TagRow                `protobuf:"bytes,1,opt,name=tag_row,json=tagRow,proto3" json:"tag_row,omitempty"`
	Children      []*TagNode             `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagNode) Reset() {
	*x = TagNode{}
	mi := &file_v1_shared_tagnode_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagNode) ProtoMessage() {}

func (x *TagNode) ProtoReflect() protoreflect.Message {
	mi := &file_v1_shared_tagnode_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagNode.ProtoReflect.Descriptor instead.
func (*TagNode) Descriptor() ([]byte, []int) {
	return file_v1_shared_tagnode_proto_rawDescGZIP(), []int{0}
}

func (x *TagNode) GetTagRow() *TagRow {
	if x != nil {
		return x.TagRow
	}
	return nil
}

func (x *TagNode) GetChildren() []*TagNode {
	if x != nil {
		return x.Children
	}
	return nil
}

var File_v1_shared_tagnode_proto protoreflect.FileDescriptor

const file_v1_shared_tagnode_proto_rawDesc = "" +
	"\n" +
	"\x17v1/shared/tagnode.proto\x12\tshared.v1\x1a\x16v1/shared/tagrow.proto\"e\n" +
	"\aTagNode\x12*\n" +
	"\atag_row\x18\x01 \x01(\v2\x11.shared.v1.TagRowR\x06tagRow\x12.\n" +
	"\bchildren\x18\x02 \x03(\v2\x12.shared.v1.TagNodeR\bchildrenBDZBgithub.com/studyguides-com/study-guides-api/api/v1/shared;sharedv1b\x06proto3"

var (
	file_v1_shared_tagnode_proto_rawDescOnce sync.Once
	file_v1_shared_tagnode_proto_rawDescData []byte
)

func file_v1_shared_tagnode_proto_rawDescGZIP() []byte {
	file_v1_shared_tagnode_proto_rawDescOnce.Do(func() {
		file_v1_shared_tagnode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_shared_tagnode_proto_rawDesc), len(file_v1_shared_tagnode_proto_rawDesc)))
	})
	return file_v1_shared_tagnode_proto_rawDescData
}

var file_v1_shared_tagnode_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_shared_tagnode_proto_goTypes = []any{
	(*TagNode)(nil), // 0: shared.v1.TagNode
	(*TagRow)(nil),  // 1: shared.v1.TagRow
}
var file_v1_shared_tagnode_proto_depIdxs = []int32{
	1, // 0: shared.v1.TagNode.tag_row:type_name -> shared.v1.TagRow
	0, // 1: shared.v1.TagNode.children:type_name -> shared.v1.TagNode
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_shared_tagnode_proto_init() }
func file_v1_shared_tagnode_proto_init() {
	if File_v1_shared_tagnode_proto != nil {
		return
	}
	file_v1_shared_tagrow_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_shared_tagnode_proto_rawDesc), len(file_v1_shared_tagnode_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_shared_tagnode_proto_goTypes,
		DependencyIndexes: file_v1_shared_tagnode_proto_depIdxs,
		MessageInfos:      file_v1_shared_tagnode_proto_msgTypes,
	}.Build()
	File_v1_shared_tagnode_proto = out.File
	file_v1_shared_tagnode_proto_goTypes = nil
	file_v1_shared_tagnode_proto_depIdxs = nil
}
