// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/shared/tagrow.proto

package sharedv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TagRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentTagId   string                 `protobuf:"bytes,2,opt,name=parent_tag_id,json=parentTagId,proto3" json:"parent_tag_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type          TagType                `protobuf:"varint,4,opt,name=type,proto3,enum=shared.v1.TagType" json:"type,omitempty"`
	Public        bool                   `protobuf:"varint,5,opt,name=public,proto3" json:"public,omitempty"`
	Context       ContextType            `protobuf:"varint,6,opt,name=context,proto3,enum=shared.v1.ContextType" json:"context,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	HasChildren   bool                   `protobuf:"varint,8,opt,name=has_children,json=hasChildren,proto3" json:"has_children,omitempty"`
	HasQuestions  bool                   `protobuf:"varint,10,opt,name=has_questions,json=hasQuestions,proto3" json:"has_questions,omitempty"`
	Level         int32                  `protobuf:"varint,11,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagRow) Reset() {
	*x = TagRow{}
	mi := &file_v1_shared_tagrow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagRow) ProtoMessage() {}

func (x *TagRow) ProtoReflect() protoreflect.Message {
	mi := &file_v1_shared_tagrow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagRow.ProtoReflect.Descriptor instead.
func (*TagRow) Descriptor() ([]byte, []int) {
	return file_v1_shared_tagrow_proto_rawDescGZIP(), []int{0}
}

func (x *TagRow) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TagRow) GetParentTagId() string {
	if x != nil {
		return x.ParentTagId
	}
	return ""
}

func (x *TagRow) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagRow) GetType() TagType {
	if x != nil {
		return x.Type
	}
	return TagType_Category
}

func (x *TagRow) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

func (x *TagRow) GetContext() ContextType {
	if x != nil {
		return x.Context
	}
	return ContextType_Colleges
}

func (x *TagRow) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TagRow) GetHasChildren() bool {
	if x != nil {
		return x.HasChildren
	}
	return false
}

func (x *TagRow) GetHasQuestions() bool {
	if x != nil {
		return x.HasQuestions
	}
	return false
}

func (x *TagRow) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

var File_v1_shared_tagrow_proto protoreflect.FileDescriptor

const file_v1_shared_tagrow_proto_rawDesc = "" +
	"\n" +
	"\x16v1/shared/tagrow.proto\x12\tshared.v1\x1a\x17v1/shared/tagtype.proto\x1a\x1bv1/shared/contexttype.proto\"\xc2\x02\n" +
	"\x06TagRow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\rparent_tag_id\x18\x02 \x01(\tR\vparentTagId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12&\n" +
	"\x04type\x18\x04 \x01(\x0e2\x12.shared.v1.TagTypeR\x04type\x12\x16\n" +
	"\x06public\x18\x05 \x01(\bR\x06public\x120\n" +
	"\acontext\x18\x06 \x01(\x0e2\x16.shared.v1.ContextTypeR\acontext\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12!\n" +
	"\fhas_children\x18\b \x01(\bR\vhasChildren\x12#\n" +
	"\rhas_questions\x18\n" +
	" \x01(\bR\fhasQuestions\x12\x14\n" +
	"\x05level\x18\v \x01(\x05R\x05levelBDZBgithub.com/studyguides-com/study-guides-api/api/v1/shared;sharedv1b\x06proto3"

var (
	file_v1_shared_tagrow_proto_rawDescOnce sync.Once
	file_v1_shared_tagrow_proto_rawDescData []byte
)

func file_v1_shared_tagrow_proto_rawDescGZIP() []byte {
	file_v1_shared_tagrow_proto_rawDescOnce.Do(func() {
		file_v1_shared_tagrow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_shared_tagrow_proto_rawDesc), len(file_v1_shared_tagrow_proto_rawDesc)))
	})
	return file_v1_shared_tagrow_proto_rawDescData
}

var file_v1_shared_tagrow_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_shared_tagrow_proto_goTypes = []any{
	(*TagRow)(nil),   // 0: shared.v1.TagRow
	(TagType)(0),     // 1: shared.v1.TagType
	(ContextType)(0), // 2: shared.v1.ContextType
}
var file_v1_shared_tagrow_proto_depIdxs = []int32{
	1, // 0: shared.v1.TagRow.type:type_name -> shared.v1.TagType
	2, // 1: shared.v1.TagRow.context:type_name -> shared.v1.ContextType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_shared_tagrow_proto_init() }
func file_v1_shared_tagrow_proto_init() {
	if File_v1_shared_tagrow_proto != nil {
		return
	}
	file_v1_shared_tagtype_proto_init()
	file_v1_shared_contexttype_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_shared_tagrow_proto_rawDesc), len(file_v1_shared_tagrow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_shared_tagrow_proto_goTypes,
		DependencyIndexes: file_v1_shared_tagrow_proto_depIdxs,
		MessageInfos:      file_v1_shared_tagrow_proto_msgTypes,
	}.Build()
	File_v1_shared_tagrow_proto = out.File
	file_v1_shared_tagrow_proto_goTypes = nil
	file_v1_shared_tagrow_proto_depIdxs = nil
}
