// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/shared/tagsearchresult.proto

package sharedv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TagSearchPath struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagSearchPath) Reset() {
	*x = TagSearchPath{}
	mi := &file_v1_shared_tagsearchresult_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagSearchPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagSearchPath) ProtoMessage() {}

func (x *TagSearchPath) ProtoReflect() protoreflect.Message {
	mi := &file_v1_shared_tagsearchresult_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagSearchPath.ProtoReflect.Descriptor instead.
func (*TagSearchPath) Descriptor() ([]byte, []int) {
	return file_v1_shared_tagsearchresult_proto_rawDescGZIP(), []int{0}
}

func (x *TagSearchPath) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TagSearchPath) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagSearchPath) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type TagSearchResult struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description        string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type               string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	HasQuestions       bool                   `protobuf:"varint,5,opt,name=has_questions,json=hasQuestions,proto3" json:"has_questions,omitempty"`
	ContentRating      string                 `protobuf:"bytes,6,opt,name=content_rating,json=contentRating,proto3" json:"content_rating,omitempty"`
	MetaTags           []string               `protobuf:"bytes,7,rep,name=meta_tags,json=metaTags,proto3" json:"meta_tags,omitempty"`
	ContentDescriptors []string               `protobuf:"bytes,8,rep,name=content_descriptors,json=contentDescriptors,proto3" json:"content_descriptors,omitempty"`
	TagHierarchy       []*TagSearchPath       `protobuf:"bytes,9,rep,name=tag_hierarchy,json=tagHierarchy,proto3" json:"tag_hierarchy,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TagSearchResult) Reset() {
	*x = TagSearchResult{}
	mi := &file_v1_shared_tagsearchresult_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagSearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagSearchResult) ProtoMessage() {}

func (x *TagSearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_v1_shared_tagsearchresult_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagSearchResult.ProtoReflect.Descriptor instead.
func (*TagSearchResult) Descriptor() ([]byte, []int) {
	return file_v1_shared_tagsearchresult_proto_rawDescGZIP(), []int{1}
}

func (x *TagSearchResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TagSearchResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagSearchResult) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TagSearchResult) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TagSearchResult) GetHasQuestions() bool {
	if x != nil {
		return x.HasQuestions
	}
	return false
}

func (x *TagSearchResult) GetContentRating() string {
	if x != nil {
		return x.ContentRating
	}
	return ""
}

func (x *TagSearchResult) GetMetaTags() []string {
	if x != nil {
		return x.MetaTags
	}
	return nil
}

func (x *TagSearchResult) GetContentDescriptors() []string {
	if x != nil {
		return x.ContentDescriptors
	}
	return nil
}

func (x *TagSearchResult) GetTagHierarchy() []*TagSearchPath {
	if x != nil {
		return x.TagHierarchy
	}
	return nil
}

var File_v1_shared_tagsearchresult_proto protoreflect.FileDescriptor

const file_v1_shared_tagsearchresult_proto_rawDesc = "" +
	"\n" +
	"\x1fv1/shared/tagsearchresult.proto\x12\tshared.v1\"G\n" +
	"\rTagSearchPath\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"\xc4\x02\n" +
	"\x0fTagSearchResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12#\n" +
	"\rhas_questions\x18\x05 \x01(\bR\fhasQuestions\x12%\n" +
	"\x0econtent_rating\x18\x06 \x01(\tR\rcontentRating\x12\x1b\n" +
	"\tmeta_tags\x18\a \x03(\tR\bmetaTags\x12/\n" +
	"\x13content_descriptors\x18\b \x03(\tR\x12contentDescriptors\x12=\n" +
	"\rtag_hierarchy\x18\t \x03(\v2\x18.shared.v1.TagSearchPathR\ftagHierarchyBDZBgithub.com/studyguides-com/study-guides-api/api/v1/shared;sharedv1b\x06proto3"

var (
	file_v1_shared_tagsearchresult_proto_rawDescOnce sync.Once
	file_v1_shared_tagsearchresult_proto_rawDescData []byte
)

func file_v1_shared_tagsearchresult_proto_rawDescGZIP() []byte {
	file_v1_shared_tagsearchresult_proto_rawDescOnce.Do(func() {
		file_v1_shared_tagsearchresult_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_shared_tagsearchresult_proto_rawDesc), len(file_v1_shared_tagsearchresult_proto_rawDesc)))
	})
	return file_v1_shared_tagsearchresult_proto_rawDescData
}

var file_v1_shared_tagsearchresult_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_shared_tagsearchresult_proto_goTypes = []any{
	(*TagSearchPath)(nil),   // 0: shared.v1.TagSearchPath
	(*TagSearchResult)(nil), // 1: shared.v1.TagSearchResult
}
var file_v1_shared_tagsearchresult_proto_depIdxs = []int32{
	0, // 0: shared.v1.TagSearchResult.tag_hierarchy:type_name -> shared.v1.TagSearchPath
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_shared_tagsearchresult_proto_init() }
func file_v1_shared_tagsearchresult_proto_init() {
	if File_v1_shared_tagsearchresult_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_shared_tagsearchresult_proto_rawDesc), len(file_v1_shared_tagsearchresult_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_shared_tagsearchresult_proto_goTypes,
		DependencyIndexes: file_v1_shared_tagsearchresult_proto_depIdxs,
		MessageInfos:      file_v1_shared_tagsearchresult_proto_msgTypes,
	}.Build()
	File_v1_shared_tagsearchresult_proto = out.File
	file_v1_shared_tagsearchresult_proto_goTypes = nil
	file_v1_shared_tagsearchresult_proto_depIdxs = nil
}
