// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/shared/tagsearchresult.proto

package sharedv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TagSearchPath struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          TagType                `protobuf:"varint,3,opt,name=type,proto3,enum=shared.v1.TagType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagSearchPath) Reset() {
	*x = TagSearchPath{}
	mi := &file_v1_shared_tagsearchresult_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagSearchPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagSearchPath) ProtoMessage() {}

func (x *TagSearchPath) ProtoReflect() protoreflect.Message {
	mi := &file_v1_shared_tagsearchresult_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagSearchPath.ProtoReflect.Descriptor instead.
func (*TagSearchPath) Descriptor() ([]byte, []int) {
	return file_v1_shared_tagsearchresult_proto_rawDescGZIP(), []int{0}
}

func (x *TagSearchPath) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TagSearchPath) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagSearchPath) GetType() TagType {
	if x != nil {
		return x.Type
	}
	return TagType_Category
}

type TagSearchResult struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Id                        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                      TagType                `protobuf:"varint,4,opt,name=type,proto3,enum=shared.v1.TagType" json:"type,omitempty"`
	ContentRating             ContentRating          `protobuf:"varint,7,opt,name=content_rating,json=contentRating,proto3,enum=shared.v1.ContentRating" json:"content_rating,omitempty"`
	MetaTags                  []string               `protobuf:"bytes,8,rep,name=meta_tags,json=metaTags,proto3" json:"meta_tags,omitempty"`
	ContentDescriptors        []string               `protobuf:"bytes,9,rep,name=content_descriptors,json=contentDescriptors,proto3" json:"content_descriptors,omitempty"`
	Tags                      []*TagSearchPath       `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	Context                   string                 `protobuf:"bytes,11,opt,name=context,proto3" json:"context,omitempty"`
	Public                    bool                   `protobuf:"varint,12,opt,name=public,proto3" json:"public,omitempty"`
	HasQuestions              bool                   `protobuf:"varint,13,opt,name=has_questions,json=hasQuestions,proto3" json:"has_questions,omitempty"`
	HasChildren               bool                   `protobuf:"varint,14,opt,name=has_children,json=hasChildren,proto3" json:"has_children,omitempty"`
	BatchId                   string                 `protobuf:"bytes,15,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	MissingMetaTags           bool                   `protobuf:"varint,16,opt,name=missing_meta_tags,json=missingMetaTags,proto3" json:"missing_meta_tags,omitempty"`
	MissingContentRating      bool                   `protobuf:"varint,17,opt,name=missing_content_rating,json=missingContentRating,proto3" json:"missing_content_rating,omitempty"`
	MissingContentDescriptors bool                   `protobuf:"varint,18,opt,name=missing_content_descriptors,json=missingContentDescriptors,proto3" json:"missing_content_descriptors,omitempty"`
	ObjectId                  string                 `protobuf:"bytes,19,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *TagSearchResult) Reset() {
	*x = TagSearchResult{}
	mi := &file_v1_shared_tagsearchresult_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagSearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagSearchResult) ProtoMessage() {}

func (x *TagSearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_v1_shared_tagsearchresult_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagSearchResult.ProtoReflect.Descriptor instead.
func (*TagSearchResult) Descriptor() ([]byte, []int) {
	return file_v1_shared_tagsearchresult_proto_rawDescGZIP(), []int{1}
}

func (x *TagSearchResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TagSearchResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagSearchResult) GetType() TagType {
	if x != nil {
		return x.Type
	}
	return TagType_Category
}

func (x *TagSearchResult) GetContentRating() ContentRating {
	if x != nil {
		return x.ContentRating
	}
	return ContentRating_Unspecified
}

func (x *TagSearchResult) GetMetaTags() []string {
	if x != nil {
		return x.MetaTags
	}
	return nil
}

func (x *TagSearchResult) GetContentDescriptors() []string {
	if x != nil {
		return x.ContentDescriptors
	}
	return nil
}

func (x *TagSearchResult) GetTags() []*TagSearchPath {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *TagSearchResult) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *TagSearchResult) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

func (x *TagSearchResult) GetHasQuestions() bool {
	if x != nil {
		return x.HasQuestions
	}
	return false
}

func (x *TagSearchResult) GetHasChildren() bool {
	if x != nil {
		return x.HasChildren
	}
	return false
}

func (x *TagSearchResult) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *TagSearchResult) GetMissingMetaTags() bool {
	if x != nil {
		return x.MissingMetaTags
	}
	return false
}

func (x *TagSearchResult) GetMissingContentRating() bool {
	if x != nil {
		return x.MissingContentRating
	}
	return false
}

func (x *TagSearchResult) GetMissingContentDescriptors() bool {
	if x != nil {
		return x.MissingContentDescriptors
	}
	return false
}

func (x *TagSearchResult) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

var File_v1_shared_tagsearchresult_proto protoreflect.FileDescriptor

const file_v1_shared_tagsearchresult_proto_rawDesc = "" +
	"\n" +
	"\x1fv1/shared/tagsearchresult.proto\x12\tshared.v1\x1a\x17v1/shared/tagtype.proto\x1a\x1dv1/shared/contentrating.proto\"[\n" +
	"\rTagSearchPath\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\x04type\x18\x03 \x01(\x0e2\x12.shared.v1.TagTypeR\x04type\"\xee\x04\n" +
	"\x0fTagSearchResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\x04type\x18\x04 \x01(\x0e2\x12.shared.v1.TagTypeR\x04type\x12?\n" +
	"\x0econtent_rating\x18\a \x01(\x0e2\x18.shared.v1.ContentRatingR\rcontentRating\x12\x1b\n" +
	"\tmeta_tags\x18\b \x03(\tR\bmetaTags\x12/\n" +
	"\x13content_descriptors\x18\t \x03(\tR\x12contentDescriptors\x12,\n" +
	"\x04tags\x18\n" +
	" \x03(\v2\x18.shared.v1.TagSearchPathR\x04tags\x12\x18\n" +
	"\acontext\x18\v \x01(\tR\acontext\x12\x16\n" +
	"\x06public\x18\f \x01(\bR\x06public\x12#\n" +
	"\rhas_questions\x18\r \x01(\bR\fhasQuestions\x12!\n" +
	"\fhas_children\x18\x0e \x01(\bR\vhasChildren\x12\x19\n" +
	"\bbatch_id\x18\x0f \x01(\tR\abatchId\x12*\n" +
	"\x11missing_meta_tags\x18\x10 \x01(\bR\x0fmissingMetaTags\x124\n" +
	"\x16missing_content_rating\x18\x11 \x01(\bR\x14missingContentRating\x12>\n" +
	"\x1bmissing_content_descriptors\x18\x12 \x01(\bR\x19missingContentDescriptors\x12\x1b\n" +
	"\tobject_id\x18\x13 \x01(\tR\bobjectIdBDZBgithub.com/studyguides-com/study-guides-api/api/v1/shared;sharedv1b\x06proto3"

var (
	file_v1_shared_tagsearchresult_proto_rawDescOnce sync.Once
	file_v1_shared_tagsearchresult_proto_rawDescData []byte
)

func file_v1_shared_tagsearchresult_proto_rawDescGZIP() []byte {
	file_v1_shared_tagsearchresult_proto_rawDescOnce.Do(func() {
		file_v1_shared_tagsearchresult_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_shared_tagsearchresult_proto_rawDesc), len(file_v1_shared_tagsearchresult_proto_rawDesc)))
	})
	return file_v1_shared_tagsearchresult_proto_rawDescData
}

var file_v1_shared_tagsearchresult_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_shared_tagsearchresult_proto_goTypes = []any{
	(*TagSearchPath)(nil),   // 0: shared.v1.TagSearchPath
	(*TagSearchResult)(nil), // 1: shared.v1.TagSearchResult
	(TagType)(0),            // 2: shared.v1.TagType
	(ContentRating)(0),      // 3: shared.v1.ContentRating
}
var file_v1_shared_tagsearchresult_proto_depIdxs = []int32{
	2, // 0: shared.v1.TagSearchPath.type:type_name -> shared.v1.TagType
	2, // 1: shared.v1.TagSearchResult.type:type_name -> shared.v1.TagType
	3, // 2: shared.v1.TagSearchResult.content_rating:type_name -> shared.v1.ContentRating
	0, // 3: shared.v1.TagSearchResult.tags:type_name -> shared.v1.TagSearchPath
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_v1_shared_tagsearchresult_proto_init() }
func file_v1_shared_tagsearchresult_proto_init() {
	if File_v1_shared_tagsearchresult_proto != nil {
		return
	}
	file_v1_shared_tagtype_proto_init()
	file_v1_shared_contentrating_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_shared_tagsearchresult_proto_rawDesc), len(file_v1_shared_tagsearchresult_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_shared_tagsearchresult_proto_goTypes,
		DependencyIndexes: file_v1_shared_tagsearchresult_proto_depIdxs,
		MessageInfos:      file_v1_shared_tagsearchresult_proto_msgTypes,
	}.Build()
	File_v1_shared_tagsearchresult_proto = out.File
	file_v1_shared_tagsearchresult_proto_goTypes = nil
	file_v1_shared_tagsearchresult_proto_depIdxs = nil
}
