// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/shared/tagtype.proto

package sharedv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TagType int32

const (
	TagType_TAG_TYPE_UNSPECIFIED       TagType = 0
	TagType_TAG_TYPE_CATEGORY          TagType = 1
	TagType_TAG_TYPE_SUB_CATEGORY      TagType = 2
	TagType_TAG_TYPE_UNIVERSITY        TagType = 3
	TagType_TAG_TYPE_REGION            TagType = 4
	TagType_TAG_TYPE_DEPARTMENT        TagType = 5
	TagType_TAG_TYPE_COURSE            TagType = 6
	TagType_TAG_TYPE_TOPIC             TagType = 7
	TagType_TAG_TYPE_USER_STUDY_GUIDE  TagType = 8
	TagType_TAG_TYPE_USER_CONTENT      TagType = 9
	TagType_TAG_TYPE_USER_FOLDER       TagType = 10
	TagType_TAG_TYPE_USER_TOPIC        TagType = 11
	TagType_TAG_TYPE_ORGANIZATION      TagType = 12
	TagType_TAG_TYPE_CERTIFYING_AGENCY TagType = 13
	TagType_TAG_TYPE_CERTIFICATION     TagType = 14
	TagType_TAG_TYPE_MODULE            TagType = 15
	TagType_TAG_TYPE_DOMAIN            TagType = 16
	TagType_TAG_TYPE_ENTRANCE_EXAM     TagType = 17
	TagType_TAG_TYPE_AP_EXAM           TagType = 18
	TagType_TAG_TYPE_BRANCH            TagType = 19
	TagType_TAG_TYPE_INSTRUCTION_TYPE  TagType = 20
	TagType_TAG_TYPE_INSTRUCTION_GROUP TagType = 21
	TagType_TAG_TYPE_INSTRUCTION       TagType = 22
	TagType_TAG_TYPE_CHAPTER           TagType = 23
	TagType_TAG_TYPE_SECTION           TagType = 24
)

// Enum value maps for TagType.
var (
	TagType_name = map[int32]string{
		0:  "TAG_TYPE_UNSPECIFIED",
		1:  "TAG_TYPE_CATEGORY",
		2:  "TAG_TYPE_SUB_CATEGORY",
		3:  "TAG_TYPE_UNIVERSITY",
		4:  "TAG_TYPE_REGION",
		5:  "TAG_TYPE_DEPARTMENT",
		6:  "TAG_TYPE_COURSE",
		7:  "TAG_TYPE_TOPIC",
		8:  "TAG_TYPE_USER_STUDY_GUIDE",
		9:  "TAG_TYPE_USER_CONTENT",
		10: "TAG_TYPE_USER_FOLDER",
		11: "TAG_TYPE_USER_TOPIC",
		12: "TAG_TYPE_ORGANIZATION",
		13: "TAG_TYPE_CERTIFYING_AGENCY",
		14: "TAG_TYPE_CERTIFICATION",
		15: "TAG_TYPE_MODULE",
		16: "TAG_TYPE_DOMAIN",
		17: "TAG_TYPE_ENTRANCE_EXAM",
		18: "TAG_TYPE_AP_EXAM",
		19: "TAG_TYPE_BRANCH",
		20: "TAG_TYPE_INSTRUCTION_TYPE",
		21: "TAG_TYPE_INSTRUCTION_GROUP",
		22: "TAG_TYPE_INSTRUCTION",
		23: "TAG_TYPE_CHAPTER",
		24: "TAG_TYPE_SECTION",
	}
	TagType_value = map[string]int32{
		"TAG_TYPE_UNSPECIFIED":       0,
		"TAG_TYPE_CATEGORY":          1,
		"TAG_TYPE_SUB_CATEGORY":      2,
		"TAG_TYPE_UNIVERSITY":        3,
		"TAG_TYPE_REGION":            4,
		"TAG_TYPE_DEPARTMENT":        5,
		"TAG_TYPE_COURSE":            6,
		"TAG_TYPE_TOPIC":             7,
		"TAG_TYPE_USER_STUDY_GUIDE":  8,
		"TAG_TYPE_USER_CONTENT":      9,
		"TAG_TYPE_USER_FOLDER":       10,
		"TAG_TYPE_USER_TOPIC":        11,
		"TAG_TYPE_ORGANIZATION":      12,
		"TAG_TYPE_CERTIFYING_AGENCY": 13,
		"TAG_TYPE_CERTIFICATION":     14,
		"TAG_TYPE_MODULE":            15,
		"TAG_TYPE_DOMAIN":            16,
		"TAG_TYPE_ENTRANCE_EXAM":     17,
		"TAG_TYPE_AP_EXAM":           18,
		"TAG_TYPE_BRANCH":            19,
		"TAG_TYPE_INSTRUCTION_TYPE":  20,
		"TAG_TYPE_INSTRUCTION_GROUP": 21,
		"TAG_TYPE_INSTRUCTION":       22,
		"TAG_TYPE_CHAPTER":           23,
		"TAG_TYPE_SECTION":           24,
	}
)

func (x TagType) Enum() *TagType {
	p := new(TagType)
	*p = x
	return p
}

func (x TagType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TagType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_shared_tagtype_proto_enumTypes[0].Descriptor()
}

func (TagType) Type() protoreflect.EnumType {
	return &file_v1_shared_tagtype_proto_enumTypes[0]
}

func (x TagType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TagType.Descriptor instead.
func (TagType) EnumDescriptor() ([]byte, []int) {
	return file_v1_shared_tagtype_proto_rawDescGZIP(), []int{0}
}

var File_v1_shared_tagtype_proto protoreflect.FileDescriptor

const file_v1_shared_tagtype_proto_rawDesc = "" +
	"\n" +
	"\x17v1/shared/tagtype.proto\x12\tshared.v1*\xff\x04\n" +
	"\aTagType\x12\x18\n" +
	"\x14TAG_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TAG_TYPE_CATEGORY\x10\x01\x12\x19\n" +
	"\x15TAG_TYPE_SUB_CATEGORY\x10\x02\x12\x17\n" +
	"\x13TAG_TYPE_UNIVERSITY\x10\x03\x12\x13\n" +
	"\x0fTAG_TYPE_REGION\x10\x04\x12\x17\n" +
	"\x13TAG_TYPE_DEPARTMENT\x10\x05\x12\x13\n" +
	"\x0fTAG_TYPE_COURSE\x10\x06\x12\x12\n" +
	"\x0eTAG_TYPE_TOPIC\x10\a\x12\x1d\n" +
	"\x19TAG_TYPE_USER_STUDY_GUIDE\x10\b\x12\x19\n" +
	"\x15TAG_TYPE_USER_CONTENT\x10\t\x12\x18\n" +
	"\x14TAG_TYPE_USER_FOLDER\x10\n" +
	"\x12\x17\n" +
	"\x13TAG_TYPE_USER_TOPIC\x10\v\x12\x19\n" +
	"\x15TAG_TYPE_ORGANIZATION\x10\f\x12\x1e\n" +
	"\x1aTAG_TYPE_CERTIFYING_AGENCY\x10\r\x12\x1a\n" +
	"\x16TAG_TYPE_CERTIFICATION\x10\x0e\x12\x13\n" +
	"\x0fTAG_TYPE_MODULE\x10\x0f\x12\x13\n" +
	"\x0fTAG_TYPE_DOMAIN\x10\x10\x12\x1a\n" +
	"\x16TAG_TYPE_ENTRANCE_EXAM\x10\x11\x12\x14\n" +
	"\x10TAG_TYPE_AP_EXAM\x10\x12\x12\x13\n" +
	"\x0fTAG_TYPE_BRANCH\x10\x13\x12\x1d\n" +
	"\x19TAG_TYPE_INSTRUCTION_TYPE\x10\x14\x12\x1e\n" +
	"\x1aTAG_TYPE_INSTRUCTION_GROUP\x10\x15\x12\x18\n" +
	"\x14TAG_TYPE_INSTRUCTION\x10\x16\x12\x14\n" +
	"\x10TAG_TYPE_CHAPTER\x10\x17\x12\x14\n" +
	"\x10TAG_TYPE_SECTION\x10\x18BDZBgithub.com/studyguides-com/study-guides-api/api/v1/shared;sharedv1b\x06proto3"

var (
	file_v1_shared_tagtype_proto_rawDescOnce sync.Once
	file_v1_shared_tagtype_proto_rawDescData []byte
)

func file_v1_shared_tagtype_proto_rawDescGZIP() []byte {
	file_v1_shared_tagtype_proto_rawDescOnce.Do(func() {
		file_v1_shared_tagtype_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_shared_tagtype_proto_rawDesc), len(file_v1_shared_tagtype_proto_rawDesc)))
	})
	return file_v1_shared_tagtype_proto_rawDescData
}

var file_v1_shared_tagtype_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_shared_tagtype_proto_goTypes = []any{
	(TagType)(0), // 0: shared.v1.TagType
}
var file_v1_shared_tagtype_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_shared_tagtype_proto_init() }
func file_v1_shared_tagtype_proto_init() {
	if File_v1_shared_tagtype_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_shared_tagtype_proto_rawDesc), len(file_v1_shared_tagtype_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_shared_tagtype_proto_goTypes,
		DependencyIndexes: file_v1_shared_tagtype_proto_depIdxs,
		EnumInfos:         file_v1_shared_tagtype_proto_enumTypes,
	}.Build()
	File_v1_shared_tagtype_proto = out.File
	file_v1_shared_tagtype_proto_goTypes = nil
	file_v1_shared_tagtype_proto_depIdxs = nil
}
