// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/shared/tagtype.proto

package sharedv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TagType int32

const (
	TagType_Category          TagType = 0
	TagType_SubCategory       TagType = 1
	TagType_University        TagType = 2
	TagType_Region            TagType = 3
	TagType_Department        TagType = 4
	TagType_Course            TagType = 5
	TagType_Topic             TagType = 6
	TagType_UserStudyGuide    TagType = 7
	TagType_UserContent       TagType = 8
	TagType_UserFolder        TagType = 9
	TagType_UserTopic         TagType = 10
	TagType_Organization      TagType = 11
	TagType_Certifying_Agency TagType = 12
	TagType_Certification     TagType = 13
	TagType_Module            TagType = 14
	TagType_Domain            TagType = 15
	TagType_Entrance_Exam     TagType = 16
	TagType_AP_Exam           TagType = 17
	TagType_Branch            TagType = 18
	TagType_Instruction_Type  TagType = 19
	TagType_Instruction_Group TagType = 20
	TagType_Instruction       TagType = 21
	TagType_Chapter           TagType = 22
	TagType_Section           TagType = 23
)

// Enum value maps for TagType.
var (
	TagType_name = map[int32]string{
		0:  "Category",
		1:  "SubCategory",
		2:  "University",
		3:  "Region",
		4:  "Department",
		5:  "Course",
		6:  "Topic",
		7:  "UserStudyGuide",
		8:  "UserContent",
		9:  "UserFolder",
		10: "UserTopic",
		11: "Organization",
		12: "Certifying_Agency",
		13: "Certification",
		14: "Module",
		15: "Domain",
		16: "Entrance_Exam",
		17: "AP_Exam",
		18: "Branch",
		19: "Instruction_Type",
		20: "Instruction_Group",
		21: "Instruction",
		22: "Chapter",
		23: "Section",
	}
	TagType_value = map[string]int32{
		"Category":          0,
		"SubCategory":       1,
		"University":        2,
		"Region":            3,
		"Department":        4,
		"Course":            5,
		"Topic":             6,
		"UserStudyGuide":    7,
		"UserContent":       8,
		"UserFolder":        9,
		"UserTopic":         10,
		"Organization":      11,
		"Certifying_Agency": 12,
		"Certification":     13,
		"Module":            14,
		"Domain":            15,
		"Entrance_Exam":     16,
		"AP_Exam":           17,
		"Branch":            18,
		"Instruction_Type":  19,
		"Instruction_Group": 20,
		"Instruction":       21,
		"Chapter":           22,
		"Section":           23,
	}
)

func (x TagType) Enum() *TagType {
	p := new(TagType)
	*p = x
	return p
}

func (x TagType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TagType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_shared_tagtype_proto_enumTypes[0].Descriptor()
}

func (TagType) Type() protoreflect.EnumType {
	return &file_v1_shared_tagtype_proto_enumTypes[0]
}

func (x TagType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TagType.Descriptor instead.
func (TagType) EnumDescriptor() ([]byte, []int) {
	return file_v1_shared_tagtype_proto_rawDescGZIP(), []int{0}
}

var File_v1_shared_tagtype_proto protoreflect.FileDescriptor

const file_v1_shared_tagtype_proto_rawDesc = "" +
	"\n" +
	"\x17v1/shared/tagtype.proto\x12\tshared.v1*\x87\x03\n" +
	"\aTagType\x12\f\n" +
	"\bCategory\x10\x00\x12\x0f\n" +
	"\vSubCategory\x10\x01\x12\x0e\n" +
	"\n" +
	"University\x10\x02\x12\n" +
	"\n" +
	"\x06Region\x10\x03\x12\x0e\n" +
	"\n" +
	"Department\x10\x04\x12\n" +
	"\n" +
	"\x06Course\x10\x05\x12\t\n" +
	"\x05Topic\x10\x06\x12\x12\n" +
	"\x0eUserStudyGuide\x10\a\x12\x0f\n" +
	"\vUserContent\x10\b\x12\x0e\n" +
	"\n" +
	"UserFolder\x10\t\x12\r\n" +
	"\tUserTopic\x10\n" +
	"\x12\x10\n" +
	"\fOrganization\x10\v\x12\x15\n" +
	"\x11Certifying_Agency\x10\f\x12\x11\n" +
	"\rCertification\x10\r\x12\n" +
	"\n" +
	"\x06Module\x10\x0e\x12\n" +
	"\n" +
	"\x06Domain\x10\x0f\x12\x11\n" +
	"\rEntrance_Exam\x10\x10\x12\v\n" +
	"\aAP_Exam\x10\x11\x12\n" +
	"\n" +
	"\x06Branch\x10\x12\x12\x14\n" +
	"\x10Instruction_Type\x10\x13\x12\x15\n" +
	"\x11Instruction_Group\x10\x14\x12\x0f\n" +
	"\vInstruction\x10\x15\x12\v\n" +
	"\aChapter\x10\x16\x12\v\n" +
	"\aSection\x10\x17BDZBgithub.com/studyguides-com/study-guides-api/api/v1/shared;sharedv1b\x06proto3"

var (
	file_v1_shared_tagtype_proto_rawDescOnce sync.Once
	file_v1_shared_tagtype_proto_rawDescData []byte
)

func file_v1_shared_tagtype_proto_rawDescGZIP() []byte {
	file_v1_shared_tagtype_proto_rawDescOnce.Do(func() {
		file_v1_shared_tagtype_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_shared_tagtype_proto_rawDesc), len(file_v1_shared_tagtype_proto_rawDesc)))
	})
	return file_v1_shared_tagtype_proto_rawDescData
}

var file_v1_shared_tagtype_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_shared_tagtype_proto_goTypes = []any{
	(TagType)(0), // 0: shared.v1.TagType
}
var file_v1_shared_tagtype_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_shared_tagtype_proto_init() }
func file_v1_shared_tagtype_proto_init() {
	if File_v1_shared_tagtype_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_shared_tagtype_proto_rawDesc), len(file_v1_shared_tagtype_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_shared_tagtype_proto_goTypes,
		DependencyIndexes: file_v1_shared_tagtype_proto_depIdxs,
		EnumInfos:         file_v1_shared_tagtype_proto_enumTypes,
	}.Build()
	File_v1_shared_tagtype_proto = out.File
	file_v1_shared_tagtype_proto_goTypes = nil
	file_v1_shared_tagtype_proto_depIdxs = nil
}
