// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/v1/shared/user.proto

package sharedv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRole int32

const (
	UserRole_USER_ROLE_UNSPECIFIED UserRole = 0
	UserRole_USER_ROLE_ADMIN       UserRole = 1
	UserRole_USER_ROLE_USER        UserRole = 2
	UserRole_USER_ROLE_FREELANCER  UserRole = 3
	UserRole_USER_ROLE_TESTER      UserRole = 4
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "USER_ROLE_UNSPECIFIED",
		1: "USER_ROLE_ADMIN",
		2: "USER_ROLE_USER",
		3: "USER_ROLE_FREELANCER",
		4: "USER_ROLE_TESTER",
	}
	UserRole_value = map[string]int32{
		"USER_ROLE_UNSPECIFIED": 0,
		"USER_ROLE_ADMIN":       1,
		"USER_ROLE_USER":        2,
		"USER_ROLE_FREELANCER":  3,
		"USER_ROLE_TESTER":      4,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_shared_user_proto_enumTypes[0].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_api_v1_shared_user_proto_enumTypes[0]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_shared_user_proto_rawDescGZIP(), []int{0}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	GamerTag      *string                `protobuf:"bytes,3,opt,name=gamer_tag,json=gamerTag,proto3,oneof" json:"gamer_tag,omitempty"`
	Email         *string                `protobuf:"bytes,4,opt,name=email,proto3,oneof" json:"email,omitempty"`
	EmailVerified *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=email_verified,json=emailVerified,proto3,oneof" json:"email_verified,omitempty"`
	Image         *string                `protobuf:"bytes,6,opt,name=image,proto3,oneof" json:"image,omitempty"`
	ContentTagId  *string                `protobuf:"bytes,7,opt,name=content_tag_id,json=contentTagId,proto3,oneof" json:"content_tag_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_v1_shared_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_shared_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_v1_shared_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *User) GetGamerTag() string {
	if x != nil && x.GamerTag != nil {
		return *x.GamerTag
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *User) GetEmailVerified() *timestamppb.Timestamp {
	if x != nil {
		return x.EmailVerified
	}
	return nil
}

func (x *User) GetImage() string {
	if x != nil && x.Image != nil {
		return *x.Image
	}
	return ""
}

func (x *User) GetContentTagId() string {
	if x != nil && x.ContentTagId != nil {
		return *x.ContentTagId
	}
	return ""
}

var File_api_v1_shared_user_proto protoreflect.FileDescriptor

const file_api_v1_shared_user_proto_rawDesc = "" +
	"\n" +
	"\x18api/v1/shared/user.proto\x12\tshared.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcb\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12 \n" +
	"\tgamer_tag\x18\x03 \x01(\tH\x01R\bgamerTag\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x04 \x01(\tH\x02R\x05email\x88\x01\x01\x12F\n" +
	"\x0eemail_verified\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\remailVerified\x88\x01\x01\x12\x19\n" +
	"\x05image\x18\x06 \x01(\tH\x04R\x05image\x88\x01\x01\x12)\n" +
	"\x0econtent_tag_id\x18\a \x01(\tH\x05R\fcontentTagId\x88\x01\x01B\a\n" +
	"\x05_nameB\f\n" +
	"\n" +
	"_gamer_tagB\b\n" +
	"\x06_emailB\x11\n" +
	"\x0f_email_verifiedB\b\n" +
	"\x06_imageB\x11\n" +
	"\x0f_content_tag_id*~\n" +
	"\bUserRole\x12\x19\n" +
	"\x15USER_ROLE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fUSER_ROLE_ADMIN\x10\x01\x12\x12\n" +
	"\x0eUSER_ROLE_USER\x10\x02\x12\x18\n" +
	"\x14USER_ROLE_FREELANCER\x10\x03\x12\x14\n" +
	"\x10USER_ROLE_TESTER\x10\x04BDZBgithub.com/studyguides-com/study-guides-api/api/v1/shared;sharedv1b\x06proto3"

var (
	file_api_v1_shared_user_proto_rawDescOnce sync.Once
	file_api_v1_shared_user_proto_rawDescData []byte
)

func file_api_v1_shared_user_proto_rawDescGZIP() []byte {
	file_api_v1_shared_user_proto_rawDescOnce.Do(func() {
		file_api_v1_shared_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_shared_user_proto_rawDesc), len(file_api_v1_shared_user_proto_rawDesc)))
	})
	return file_api_v1_shared_user_proto_rawDescData
}

var file_api_v1_shared_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1_shared_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_v1_shared_user_proto_goTypes = []any{
	(UserRole)(0),                 // 0: shared.v1.UserRole
	(*User)(nil),                  // 1: shared.v1.User
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_api_v1_shared_user_proto_depIdxs = []int32{
	2, // 0: shared.v1.User.email_verified:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_v1_shared_user_proto_init() }
func file_api_v1_shared_user_proto_init() {
	if File_api_v1_shared_user_proto != nil {
		return
	}
	file_api_v1_shared_user_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_shared_user_proto_rawDesc), len(file_api_v1_shared_user_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_shared_user_proto_goTypes,
		DependencyIndexes: file_api_v1_shared_user_proto_depIdxs,
		EnumInfos:         file_api_v1_shared_user_proto_enumTypes,
		MessageInfos:      file_api_v1_shared_user_proto_msgTypes,
	}.Build()
	File_api_v1_shared_user_proto = out.File
	file_api_v1_shared_user_proto_goTypes = nil
	file_api_v1_shared_user_proto_depIdxs = nil
}
