// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/shared/usersearchresult.proto

package sharedv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserSearchResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email            string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	GamerTag         string                 `protobuf:"bytes,4,opt,name=gamer_tag,json=gamerTag,proto3" json:"gamer_tag,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StripeCustomerId string                 `protobuf:"bytes,6,opt,name=stripe_customer_id,json=stripeCustomerId,proto3" json:"stripe_customer_id,omitempty"`
	ObjectId         string                 `protobuf:"bytes,7,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserSearchResult) Reset() {
	*x = UserSearchResult{}
	mi := &file_v1_shared_usersearchresult_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSearchResult) ProtoMessage() {}

func (x *UserSearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_v1_shared_usersearchresult_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSearchResult.ProtoReflect.Descriptor instead.
func (*UserSearchResult) Descriptor() ([]byte, []int) {
	return file_v1_shared_usersearchresult_proto_rawDescGZIP(), []int{0}
}

func (x *UserSearchResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserSearchResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserSearchResult) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserSearchResult) GetGamerTag() string {
	if x != nil {
		return x.GamerTag
	}
	return ""
}

func (x *UserSearchResult) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserSearchResult) GetStripeCustomerId() string {
	if x != nil {
		return x.StripeCustomerId
	}
	return ""
}

func (x *UserSearchResult) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

var File_v1_shared_usersearchresult_proto protoreflect.FileDescriptor

const file_v1_shared_usersearchresult_proto_rawDesc = "" +
	"\n" +
	" v1/shared/usersearchresult.proto\x12\tshared.v1\"\xd3\x01\n" +
	"\x10UserSearchResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1b\n" +
	"\tgamer_tag\x18\x04 \x01(\tR\bgamerTag\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12,\n" +
	"\x12stripe_customer_id\x18\x06 \x01(\tR\x10stripeCustomerId\x12\x1b\n" +
	"\tobject_id\x18\a \x01(\tR\bobjectIdBDZBgithub.com/studyguides-com/study-guides-api/api/v1/shared;sharedv1b\x06proto3"

var (
	file_v1_shared_usersearchresult_proto_rawDescOnce sync.Once
	file_v1_shared_usersearchresult_proto_rawDescData []byte
)

func file_v1_shared_usersearchresult_proto_rawDescGZIP() []byte {
	file_v1_shared_usersearchresult_proto_rawDescOnce.Do(func() {
		file_v1_shared_usersearchresult_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_shared_usersearchresult_proto_rawDesc), len(file_v1_shared_usersearchresult_proto_rawDesc)))
	})
	return file_v1_shared_usersearchresult_proto_rawDescData
}

var file_v1_shared_usersearchresult_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_shared_usersearchresult_proto_goTypes = []any{
	(*UserSearchResult)(nil), // 0: shared.v1.UserSearchResult
}
var file_v1_shared_usersearchresult_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_shared_usersearchresult_proto_init() }
func file_v1_shared_usersearchresult_proto_init() {
	if File_v1_shared_usersearchresult_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_shared_usersearchresult_proto_rawDesc), len(file_v1_shared_usersearchresult_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_shared_usersearchresult_proto_goTypes,
		DependencyIndexes: file_v1_shared_usersearchresult_proto_depIdxs,
		MessageInfos:      file_v1_shared_usersearchresult_proto_msgTypes,
	}.Build()
	File_v1_shared_usersearchresult_proto = out.File
	file_v1_shared_usersearchresult_proto_goTypes = nil
	file_v1_shared_usersearchresult_proto_depIdxs = nil
}
