// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/indexing/indexing.proto

package indexingv1

import (
	shared "github.com/studyguides-com/study-guides-api/api/v1/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to trigger an indexing job
type TriggerIndexingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of object to index (defaults to "Tag")
	ObjectType string `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	// If true, forces complete reindex ignoring change detection
	// If false, only indexes changed items (incremental mode)
	Force         bool `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerIndexingRequest) Reset() {
	*x = TriggerIndexingRequest{}
	mi := &file_v1_indexing_indexing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerIndexingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerIndexingRequest) ProtoMessage() {}

func (x *TriggerIndexingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_indexing_indexing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerIndexingRequest.ProtoReflect.Descriptor instead.
func (*TriggerIndexingRequest) Descriptor() ([]byte, []int) {
	return file_v1_indexing_indexing_proto_rawDescGZIP(), []int{0}
}

func (x *TriggerIndexingRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *TriggerIndexingRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// Response from triggering an indexing job
type TriggerIndexingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique job ID for tracking
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Initial status of the job
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// Human-readable message about the job
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Timestamp when job was started
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerIndexingResponse) Reset() {
	*x = TriggerIndexingResponse{}
	mi := &file_v1_indexing_indexing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerIndexingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerIndexingResponse) ProtoMessage() {}

func (x *TriggerIndexingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_indexing_indexing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerIndexingResponse.ProtoReflect.Descriptor instead.
func (*TriggerIndexingResponse) Descriptor() ([]byte, []int) {
	return file_v1_indexing_indexing_proto_rawDescGZIP(), []int{1}
}

func (x *TriggerIndexingResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *TriggerIndexingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TriggerIndexingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TriggerIndexingResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

// Request to get status of a specific job
type GetJobStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Job ID to query
	JobId         string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusRequest) Reset() {
	*x = GetJobStatusRequest{}
	mi := &file_v1_indexing_indexing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusRequest) ProtoMessage() {}

func (x *GetJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_indexing_indexing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusRequest.ProtoReflect.Descriptor instead.
func (*GetJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_v1_indexing_indexing_proto_rawDescGZIP(), []int{2}
}

func (x *GetJobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// Response with job status details
type GetJobStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Job ID
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Current status (Running, Completed, Failed)
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// Job description
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// When the job started
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// When the job completed (if applicable)
	CompletedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	// Error message if job failed
	ErrorMessage string `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Job metadata
	Metadata      *JobMetadata `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusResponse) Reset() {
	*x = GetJobStatusResponse{}
	mi := &file_v1_indexing_indexing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusResponse) ProtoMessage() {}

func (x *GetJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_indexing_indexing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusResponse.ProtoReflect.Descriptor instead.
func (*GetJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_v1_indexing_indexing_proto_rawDescGZIP(), []int{3}
}

func (x *GetJobStatusResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetJobStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetJobStatusResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetJobStatusResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *GetJobStatusResponse) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *GetJobStatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetJobStatusResponse) GetMetadata() *JobMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Metadata about an indexing job
type JobMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of object being indexed
	ObjectType string `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	// Whether this is a force rebuild
	Force bool `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	// Number of items processed
	ItemsProcessed int64 `protobuf:"varint,3,opt,name=items_processed,json=itemsProcessed,proto3" json:"items_processed,omitempty"`
	// Number of items failed
	ItemsFailed int64 `protobuf:"varint,4,opt,name=items_failed,json=itemsFailed,proto3" json:"items_failed,omitempty"`
	// Additional key-value metadata
	Extra         map[string]string `protobuf:"bytes,5,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobMetadata) Reset() {
	*x = JobMetadata{}
	mi := &file_v1_indexing_indexing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobMetadata) ProtoMessage() {}

func (x *JobMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_v1_indexing_indexing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobMetadata.ProtoReflect.Descriptor instead.
func (*JobMetadata) Descriptor() ([]byte, []int) {
	return file_v1_indexing_indexing_proto_rawDescGZIP(), []int{4}
}

func (x *JobMetadata) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *JobMetadata) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *JobMetadata) GetItemsProcessed() int64 {
	if x != nil {
		return x.ItemsProcessed
	}
	return 0
}

func (x *JobMetadata) GetItemsFailed() int64 {
	if x != nil {
		return x.ItemsFailed
	}
	return 0
}

func (x *JobMetadata) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

// Request to list running jobs
type ListRunningJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunningJobsRequest) Reset() {
	*x = ListRunningJobsRequest{}
	mi := &file_v1_indexing_indexing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunningJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunningJobsRequest) ProtoMessage() {}

func (x *ListRunningJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_indexing_indexing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunningJobsRequest.ProtoReflect.Descriptor instead.
func (*ListRunningJobsRequest) Descriptor() ([]byte, []int) {
	return file_v1_indexing_indexing_proto_rawDescGZIP(), []int{5}
}

// Response with list of running jobs
type ListRunningJobsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of running jobs
	Jobs []*JobInfo `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	// Total count of running jobs
	TotalCount    int32 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunningJobsResponse) Reset() {
	*x = ListRunningJobsResponse{}
	mi := &file_v1_indexing_indexing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunningJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunningJobsResponse) ProtoMessage() {}

func (x *ListRunningJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_indexing_indexing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunningJobsResponse.ProtoReflect.Descriptor instead.
func (*ListRunningJobsResponse) Descriptor() ([]byte, []int) {
	return file_v1_indexing_indexing_proto_rawDescGZIP(), []int{6}
}

func (x *ListRunningJobsResponse) GetJobs() []*JobInfo {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListRunningJobsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// Request to list recent jobs
type ListRecentJobsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Object type to filter by (optional, returns all types if not specified)
	ObjectType string `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	// Maximum number of jobs to return (default 10)
	Limit         int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecentJobsRequest) Reset() {
	*x = ListRecentJobsRequest{}
	mi := &file_v1_indexing_indexing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecentJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecentJobsRequest) ProtoMessage() {}

func (x *ListRecentJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_indexing_indexing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecentJobsRequest.ProtoReflect.Descriptor instead.
func (*ListRecentJobsRequest) Descriptor() ([]byte, []int) {
	return file_v1_indexing_indexing_proto_rawDescGZIP(), []int{7}
}

func (x *ListRecentJobsRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *ListRecentJobsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Response with list of recent jobs
type ListRecentJobsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of recent jobs
	Jobs          []*JobInfo `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecentJobsResponse) Reset() {
	*x = ListRecentJobsResponse{}
	mi := &file_v1_indexing_indexing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecentJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecentJobsResponse) ProtoMessage() {}

func (x *ListRecentJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_indexing_indexing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecentJobsResponse.ProtoReflect.Descriptor instead.
func (*ListRecentJobsResponse) Descriptor() ([]byte, []int) {
	return file_v1_indexing_indexing_proto_rawDescGZIP(), []int{8}
}

func (x *ListRecentJobsResponse) GetJobs() []*JobInfo {
	if x != nil {
		return x.Jobs
	}
	return nil
}

// Information about an indexing job
type JobInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Job ID
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Current status
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// Job description
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// When the job started
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// When the job completed (if applicable)
	CompletedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	// Error message if failed
	ErrorMessage string `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Job metadata
	Metadata      *JobMetadata `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobInfo) Reset() {
	*x = JobInfo{}
	mi := &file_v1_indexing_indexing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobInfo) ProtoMessage() {}

func (x *JobInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v1_indexing_indexing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobInfo.ProtoReflect.Descriptor instead.
func (*JobInfo) Descriptor() ([]byte, []int) {
	return file_v1_indexing_indexing_proto_rawDescGZIP(), []int{9}
}

func (x *JobInfo) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *JobInfo) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *JobInfo) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *JobInfo) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *JobInfo) GetMetadata() *JobMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Request to trigger tag indexing with flexible filtering
type TriggerTagIndexingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If true, forces complete reindex ignoring change detection
	// If false, only indexes changed items (incremental mode)
	Force bool `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`
	// Optional filter by tag types - empty array means no filter
	// Can be used alone or combined with context_types
	TagTypes []shared.TagType `protobuf:"varint,2,rep,packed,name=tag_types,json=tagTypes,proto3,enum=shared.v1.TagType" json:"tag_types,omitempty"`
	// Optional filter by context types - empty array means no filter
	// Can be used alone or combined with tag_types
	ContextTypes  []shared.ContextType `protobuf:"varint,3,rep,packed,name=context_types,json=contextTypes,proto3,enum=shared.v1.ContextType" json:"context_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerTagIndexingRequest) Reset() {
	*x = TriggerTagIndexingRequest{}
	mi := &file_v1_indexing_indexing_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerTagIndexingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerTagIndexingRequest) ProtoMessage() {}

func (x *TriggerTagIndexingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_indexing_indexing_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerTagIndexingRequest.ProtoReflect.Descriptor instead.
func (*TriggerTagIndexingRequest) Descriptor() ([]byte, []int) {
	return file_v1_indexing_indexing_proto_rawDescGZIP(), []int{10}
}

func (x *TriggerTagIndexingRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *TriggerTagIndexingRequest) GetTagTypes() []shared.TagType {
	if x != nil {
		return x.TagTypes
	}
	return nil
}

func (x *TriggerTagIndexingRequest) GetContextTypes() []shared.ContextType {
	if x != nil {
		return x.ContextTypes
	}
	return nil
}

// Request to trigger indexing for a single specific item
type TriggerSingleIndexingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of object to index (e.g., "Tag", "Question")
	ObjectType string `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	// ID of the specific item to index
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// If true, forces complete reindex ignoring change detection
	// If false, only indexes if item has changed (incremental mode)
	Force         bool `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerSingleIndexingRequest) Reset() {
	*x = TriggerSingleIndexingRequest{}
	mi := &file_v1_indexing_indexing_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSingleIndexingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSingleIndexingRequest) ProtoMessage() {}

func (x *TriggerSingleIndexingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_indexing_indexing_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSingleIndexingRequest.ProtoReflect.Descriptor instead.
func (*TriggerSingleIndexingRequest) Descriptor() ([]byte, []int) {
	return file_v1_indexing_indexing_proto_rawDescGZIP(), []int{11}
}

func (x *TriggerSingleIndexingRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *TriggerSingleIndexingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TriggerSingleIndexingRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// Request to prune orphaned objects from the search index
type PruneIndexRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of object to prune (defaults to "Tag")
	ObjectType string `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	// Optional filter by tag types - empty array means no filter
	TagTypes []shared.TagType `protobuf:"varint,2,rep,packed,name=tag_types,json=tagTypes,proto3,enum=shared.v1.TagType" json:"tag_types,omitempty"`
	// Optional filter by context types - empty array means no filter
	ContextTypes  []shared.ContextType `protobuf:"varint,3,rep,packed,name=context_types,json=contextTypes,proto3,enum=shared.v1.ContextType" json:"context_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PruneIndexRequest) Reset() {
	*x = PruneIndexRequest{}
	mi := &file_v1_indexing_indexing_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PruneIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PruneIndexRequest) ProtoMessage() {}

func (x *PruneIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_indexing_indexing_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PruneIndexRequest.ProtoReflect.Descriptor instead.
func (*PruneIndexRequest) Descriptor() ([]byte, []int) {
	return file_v1_indexing_indexing_proto_rawDescGZIP(), []int{12}
}

func (x *PruneIndexRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *PruneIndexRequest) GetTagTypes() []shared.TagType {
	if x != nil {
		return x.TagTypes
	}
	return nil
}

func (x *PruneIndexRequest) GetContextTypes() []shared.ContextType {
	if x != nil {
		return x.ContextTypes
	}
	return nil
}

// Response from pruning the search index
type PruneIndexResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique job ID for tracking
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Initial status of the job
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// Human-readable message about the job
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Timestamp when job was started
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PruneIndexResponse) Reset() {
	*x = PruneIndexResponse{}
	mi := &file_v1_indexing_indexing_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PruneIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PruneIndexResponse) ProtoMessage() {}

func (x *PruneIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_indexing_indexing_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PruneIndexResponse.ProtoReflect.Descriptor instead.
func (*PruneIndexResponse) Descriptor() ([]byte, []int) {
	return file_v1_indexing_indexing_proto_rawDescGZIP(), []int{13}
}

func (x *PruneIndexResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *PruneIndexResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PruneIndexResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PruneIndexResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

var File_v1_indexing_indexing_proto protoreflect.FileDescriptor

const file_v1_indexing_indexing_proto_rawDesc = "" +
	"\n" +
	"\x1av1/indexing/indexing.proto\x12\vindexing.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17v1/shared/tagtype.proto\x1a\x1bv1/shared/contexttype.proto\"O\n" +
	"\x16TriggerIndexingRequest\x12\x1f\n" +
	"\vobject_type\x18\x01 \x01(\tR\n" +
	"objectType\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"\x9d\x01\n" +
	"\x17TriggerIndexingResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\",\n" +
	"\x13GetJobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\xbc\x02\n" +
	"\x14GetJobStatusResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x124\n" +
	"\bmetadata\x18\a \x01(\v2\x18.indexing.v1.JobMetadataR\bmetadata\"\x85\x02\n" +
	"\vJobMetadata\x12\x1f\n" +
	"\vobject_type\x18\x01 \x01(\tR\n" +
	"objectType\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\x12'\n" +
	"\x0fitems_processed\x18\x03 \x01(\x03R\x0eitemsProcessed\x12!\n" +
	"\fitems_failed\x18\x04 \x01(\x03R\vitemsFailed\x129\n" +
	"\x05extra\x18\x05 \x03(\v2#.indexing.v1.JobMetadata.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x18\n" +
	"\x16ListRunningJobsRequest\"d\n" +
	"\x17ListRunningJobsResponse\x12(\n" +
	"\x04jobs\x18\x01 \x03(\v2\x14.indexing.v1.JobInfoR\x04jobs\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"N\n" +
	"\x15ListRecentJobsRequest\x12\x1f\n" +
	"\vobject_type\x18\x01 \x01(\tR\n" +
	"objectType\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"B\n" +
	"\x16ListRecentJobsResponse\x12(\n" +
	"\x04jobs\x18\x01 \x03(\v2\x14.indexing.v1.JobInfoR\x04jobs\"\xaf\x02\n" +
	"\aJobInfo\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x124\n" +
	"\bmetadata\x18\a \x01(\v2\x18.indexing.v1.JobMetadataR\bmetadata\"\x9f\x01\n" +
	"\x19TriggerTagIndexingRequest\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\x12/\n" +
	"\ttag_types\x18\x02 \x03(\x0e2\x12.shared.v1.TagTypeR\btagTypes\x12;\n" +
	"\rcontext_types\x18\x03 \x03(\x0e2\x16.shared.v1.ContextTypeR\fcontextTypes\"e\n" +
	"\x1cTriggerSingleIndexingRequest\x12\x1f\n" +
	"\vobject_type\x18\x01 \x01(\tR\n" +
	"objectType\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\"\xa2\x01\n" +
	"\x11PruneIndexRequest\x12\x1f\n" +
	"\vobject_type\x18\x01 \x01(\tR\n" +
	"objectType\x12/\n" +
	"\ttag_types\x18\x02 \x03(\x0e2\x12.shared.v1.TagTypeR\btagTypes\x12;\n" +
	"\rcontext_types\x18\x03 \x03(\x0e2\x16.shared.v1.ContextTypeR\fcontextTypes\"\x98\x01\n" +
	"\x12PruneIndexResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt2\x9a\x05\n" +
	"\x0fIndexingService\x12\\\n" +
	"\x0fTriggerIndexing\x12#.indexing.v1.TriggerIndexingRequest\x1a$.indexing.v1.TriggerIndexingResponse\x12S\n" +
	"\fGetJobStatus\x12 .indexing.v1.GetJobStatusRequest\x1a!.indexing.v1.GetJobStatusResponse\x12\\\n" +
	"\x0fListRunningJobs\x12#.indexing.v1.ListRunningJobsRequest\x1a$.indexing.v1.ListRunningJobsResponse\x12Y\n" +
	"\x0eListRecentJobs\x12\".indexing.v1.ListRecentJobsRequest\x1a#.indexing.v1.ListRecentJobsResponse\x12b\n" +
	"\x12TriggerTagIndexing\x12&.indexing.v1.TriggerTagIndexingRequest\x1a$.indexing.v1.TriggerIndexingResponse\x12h\n" +
	"\x15TriggerSingleIndexing\x12).indexing.v1.TriggerSingleIndexingRequest\x1a$.indexing.v1.TriggerIndexingResponse\x12M\n" +
	"\n" +
	"PruneIndex\x12\x1e.indexing.v1.PruneIndexRequest\x1a\x1f.indexing.v1.PruneIndexResponseBHZFgithub.com/studyguides-com/study-guides-api/api/v1/indexing;indexingv1b\x06proto3"

var (
	file_v1_indexing_indexing_proto_rawDescOnce sync.Once
	file_v1_indexing_indexing_proto_rawDescData []byte
)

func file_v1_indexing_indexing_proto_rawDescGZIP() []byte {
	file_v1_indexing_indexing_proto_rawDescOnce.Do(func() {
		file_v1_indexing_indexing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_indexing_indexing_proto_rawDesc), len(file_v1_indexing_indexing_proto_rawDesc)))
	})
	return file_v1_indexing_indexing_proto_rawDescData
}

var file_v1_indexing_indexing_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_v1_indexing_indexing_proto_goTypes = []any{
	(*TriggerIndexingRequest)(nil),       // 0: indexing.v1.TriggerIndexingRequest
	(*TriggerIndexingResponse)(nil),      // 1: indexing.v1.TriggerIndexingResponse
	(*GetJobStatusRequest)(nil),          // 2: indexing.v1.GetJobStatusRequest
	(*GetJobStatusResponse)(nil),         // 3: indexing.v1.GetJobStatusResponse
	(*JobMetadata)(nil),                  // 4: indexing.v1.JobMetadata
	(*ListRunningJobsRequest)(nil),       // 5: indexing.v1.ListRunningJobsRequest
	(*ListRunningJobsResponse)(nil),      // 6: indexing.v1.ListRunningJobsResponse
	(*ListRecentJobsRequest)(nil),        // 7: indexing.v1.ListRecentJobsRequest
	(*ListRecentJobsResponse)(nil),       // 8: indexing.v1.ListRecentJobsResponse
	(*JobInfo)(nil),                      // 9: indexing.v1.JobInfo
	(*TriggerTagIndexingRequest)(nil),    // 10: indexing.v1.TriggerTagIndexingRequest
	(*TriggerSingleIndexingRequest)(nil), // 11: indexing.v1.TriggerSingleIndexingRequest
	(*PruneIndexRequest)(nil),            // 12: indexing.v1.PruneIndexRequest
	(*PruneIndexResponse)(nil),           // 13: indexing.v1.PruneIndexResponse
	nil,                                  // 14: indexing.v1.JobMetadata.ExtraEntry
	(*timestamppb.Timestamp)(nil),        // 15: google.protobuf.Timestamp
	(shared.TagType)(0),                  // 16: shared.v1.TagType
	(shared.ContextType)(0),              // 17: shared.v1.ContextType
}
var file_v1_indexing_indexing_proto_depIdxs = []int32{
	15, // 0: indexing.v1.TriggerIndexingResponse.started_at:type_name -> google.protobuf.Timestamp
	15, // 1: indexing.v1.GetJobStatusResponse.started_at:type_name -> google.protobuf.Timestamp
	15, // 2: indexing.v1.GetJobStatusResponse.completed_at:type_name -> google.protobuf.Timestamp
	4,  // 3: indexing.v1.GetJobStatusResponse.metadata:type_name -> indexing.v1.JobMetadata
	14, // 4: indexing.v1.JobMetadata.extra:type_name -> indexing.v1.JobMetadata.ExtraEntry
	9,  // 5: indexing.v1.ListRunningJobsResponse.jobs:type_name -> indexing.v1.JobInfo
	9,  // 6: indexing.v1.ListRecentJobsResponse.jobs:type_name -> indexing.v1.JobInfo
	15, // 7: indexing.v1.JobInfo.started_at:type_name -> google.protobuf.Timestamp
	15, // 8: indexing.v1.JobInfo.completed_at:type_name -> google.protobuf.Timestamp
	4,  // 9: indexing.v1.JobInfo.metadata:type_name -> indexing.v1.JobMetadata
	16, // 10: indexing.v1.TriggerTagIndexingRequest.tag_types:type_name -> shared.v1.TagType
	17, // 11: indexing.v1.TriggerTagIndexingRequest.context_types:type_name -> shared.v1.ContextType
	16, // 12: indexing.v1.PruneIndexRequest.tag_types:type_name -> shared.v1.TagType
	17, // 13: indexing.v1.PruneIndexRequest.context_types:type_name -> shared.v1.ContextType
	15, // 14: indexing.v1.PruneIndexResponse.started_at:type_name -> google.protobuf.Timestamp
	0,  // 15: indexing.v1.IndexingService.TriggerIndexing:input_type -> indexing.v1.TriggerIndexingRequest
	2,  // 16: indexing.v1.IndexingService.GetJobStatus:input_type -> indexing.v1.GetJobStatusRequest
	5,  // 17: indexing.v1.IndexingService.ListRunningJobs:input_type -> indexing.v1.ListRunningJobsRequest
	7,  // 18: indexing.v1.IndexingService.ListRecentJobs:input_type -> indexing.v1.ListRecentJobsRequest
	10, // 19: indexing.v1.IndexingService.TriggerTagIndexing:input_type -> indexing.v1.TriggerTagIndexingRequest
	11, // 20: indexing.v1.IndexingService.TriggerSingleIndexing:input_type -> indexing.v1.TriggerSingleIndexingRequest
	12, // 21: indexing.v1.IndexingService.PruneIndex:input_type -> indexing.v1.PruneIndexRequest
	1,  // 22: indexing.v1.IndexingService.TriggerIndexing:output_type -> indexing.v1.TriggerIndexingResponse
	3,  // 23: indexing.v1.IndexingService.GetJobStatus:output_type -> indexing.v1.GetJobStatusResponse
	6,  // 24: indexing.v1.IndexingService.ListRunningJobs:output_type -> indexing.v1.ListRunningJobsResponse
	8,  // 25: indexing.v1.IndexingService.ListRecentJobs:output_type -> indexing.v1.ListRecentJobsResponse
	1,  // 26: indexing.v1.IndexingService.TriggerTagIndexing:output_type -> indexing.v1.TriggerIndexingResponse
	1,  // 27: indexing.v1.IndexingService.TriggerSingleIndexing:output_type -> indexing.v1.TriggerIndexingResponse
	13, // 28: indexing.v1.IndexingService.PruneIndex:output_type -> indexing.v1.PruneIndexResponse
	22, // [22:29] is the sub-list for method output_type
	15, // [15:22] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_v1_indexing_indexing_proto_init() }
func file_v1_indexing_indexing_proto_init() {
	if File_v1_indexing_indexing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_indexing_indexing_proto_rawDesc), len(file_v1_indexing_indexing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_indexing_indexing_proto_goTypes,
		DependencyIndexes: file_v1_indexing_indexing_proto_depIdxs,
		MessageInfos:      file_v1_indexing_indexing_proto_msgTypes,
	}.Build()
	File_v1_indexing_indexing_proto = out.File
	file_v1_indexing_indexing_proto_goTypes = nil
	file_v1_indexing_indexing_proto_depIdxs = nil
}
