// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: study.proto

package study

import (
	health "github.com/studyguides-com/study-guides-api/api/study/health"
	search "github.com/studyguides-com/study-guides-api/api/study/search"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_study_proto protoreflect.FileDescriptor

const file_study_proto_rawDesc = "" +
	"\n" +
	"\vstudy.proto\x12\x05study\x1a\x13search/search.proto\x1a\x13health/health.proto2\x8f\x01\n" +
	"\fStudyService\x127\n" +
	"\x06Search\x12\x15.search.SearchRequest\x1a\x16.search.SearchResponse\x12F\n" +
	"\vHealthCheck\x12\x1a.health.HealthCheckRequest\x1a\x1b.health.HealthCheckResponseB=Z;github.com/studyguides-com/study-guides-api/api/study;studyb\x06proto3"

var file_study_proto_goTypes = []any{
	(*search.SearchRequest)(nil),       // 0: search.SearchRequest
	(*health.HealthCheckRequest)(nil),  // 1: health.HealthCheckRequest
	(*search.SearchResponse)(nil),      // 2: search.SearchResponse
	(*health.HealthCheckResponse)(nil), // 3: health.HealthCheckResponse
}
var file_study_proto_depIdxs = []int32{
	0, // 0: study.StudyService.Search:input_type -> search.SearchRequest
	1, // 1: study.StudyService.HealthCheck:input_type -> health.HealthCheckRequest
	2, // 2: study.StudyService.Search:output_type -> search.SearchResponse
	3, // 3: study.StudyService.HealthCheck:output_type -> health.HealthCheckResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_study_proto_init() }
func file_study_proto_init() {
	if File_study_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_study_proto_rawDesc), len(file_study_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_study_proto_goTypes,
		DependencyIndexes: file_study_proto_depIdxs,
	}.Build()
	File_study_proto = out.File
	file_study_proto_goTypes = nil
	file_study_proto_depIdxs = nil
}
