// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/interaction/interaction.proto

package interactionv1

import (
	shared "github.com/studyguides-com/study-guides-api/api/v1/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InteractRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	QuestionId      string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	UserId          *string                `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	StudyMethod     shared.StudyMethod     `protobuf:"varint,3,opt,name=study_method,json=studyMethod,proto3,enum=shared.v1.StudyMethod" json:"study_method,omitempty"`
	InteractionType shared.InteractionType `protobuf:"varint,4,opt,name=interaction_type,json=interactionType,proto3,enum=shared.v1.InteractionType" json:"interaction_type,omitempty"`
	DeckAssignment  shared.DeckAssignment  `protobuf:"varint,5,opt,name=deck_assignment,json=deckAssignment,proto3,enum=shared.v1.DeckAssignment" json:"deck_assignment,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InteractRequest) Reset() {
	*x = InteractRequest{}
	mi := &file_v1_interaction_interaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractRequest) ProtoMessage() {}

func (x *InteractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_interaction_interaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractRequest.ProtoReflect.Descriptor instead.
func (*InteractRequest) Descriptor() ([]byte, []int) {
	return file_v1_interaction_interaction_proto_rawDescGZIP(), []int{0}
}

func (x *InteractRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *InteractRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *InteractRequest) GetStudyMethod() shared.StudyMethod {
	if x != nil {
		return x.StudyMethod
	}
	return shared.StudyMethod(0)
}

func (x *InteractRequest) GetInteractionType() shared.InteractionType {
	if x != nil {
		return x.InteractionType
	}
	return shared.InteractionType(0)
}

func (x *InteractRequest) GetDeckAssignment() shared.DeckAssignment {
	if x != nil {
		return x.DeckAssignment
	}
	return shared.DeckAssignment(0)
}

type InteractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      *shared.Question       `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractResponse) Reset() {
	*x = InteractResponse{}
	mi := &file_v1_interaction_interaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractResponse) ProtoMessage() {}

func (x *InteractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_interaction_interaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractResponse.ProtoReflect.Descriptor instead.
func (*InteractResponse) Descriptor() ([]byte, []int) {
	return file_v1_interaction_interaction_proto_rawDescGZIP(), []int{1}
}

func (x *InteractResponse) GetQuestion() *shared.Question {
	if x != nil {
		return x.Question
	}
	return nil
}

var File_v1_interaction_interaction_proto protoreflect.FileDescriptor

const file_v1_interaction_interaction_proto_rawDesc = "" +
	"\n" +
	" v1/interaction/interaction.proto\x12\x0einteraction.v1\x1a\x18v1/shared/question.proto\x1a\x1bv1/shared/studymethod.proto\x1a\x1fv1/shared/interactiontype.proto\x1a\x1ev1/shared/deckassignment.proto\"\xa2\x02\n" +
	"\x0fInteractRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12\x1c\n" +
	"\auser_id\x18\x02 \x01(\tH\x00R\x06userId\x88\x01\x01\x129\n" +
	"\fstudy_method\x18\x03 \x01(\x0e2\x16.shared.v1.StudyMethodR\vstudyMethod\x12E\n" +
	"\x10interaction_type\x18\x04 \x01(\x0e2\x1a.shared.v1.InteractionTypeR\x0finteractionType\x12B\n" +
	"\x0fdeck_assignment\x18\x05 \x01(\x0e2\x19.shared.v1.DeckAssignmentR\x0edeckAssignmentB\n" +
	"\n" +
	"\b_user_id\"C\n" +
	"\x10InteractResponse\x12/\n" +
	"\bquestion\x18\x01 \x01(\v2\x13.shared.v1.QuestionR\bquestion2c\n" +
	"\x12InteractionService\x12M\n" +
	"\bInteract\x12\x1f.interaction.v1.InteractRequest\x1a .interaction.v1.InteractResponseBNZLgithub.com/studyguides-com/study-guides-api/api/v1/interaction;interactionv1b\x06proto3"

var (
	file_v1_interaction_interaction_proto_rawDescOnce sync.Once
	file_v1_interaction_interaction_proto_rawDescData []byte
)

func file_v1_interaction_interaction_proto_rawDescGZIP() []byte {
	file_v1_interaction_interaction_proto_rawDescOnce.Do(func() {
		file_v1_interaction_interaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_interaction_interaction_proto_rawDesc), len(file_v1_interaction_interaction_proto_rawDesc)))
	})
	return file_v1_interaction_interaction_proto_rawDescData
}

var file_v1_interaction_interaction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_interaction_interaction_proto_goTypes = []any{
	(*InteractRequest)(nil),     // 0: interaction.v1.InteractRequest
	(*InteractResponse)(nil),    // 1: interaction.v1.InteractResponse
	(shared.StudyMethod)(0),     // 2: shared.v1.StudyMethod
	(shared.InteractionType)(0), // 3: shared.v1.InteractionType
	(shared.DeckAssignment)(0),  // 4: shared.v1.DeckAssignment
	(*shared.Question)(nil),     // 5: shared.v1.Question
}
var file_v1_interaction_interaction_proto_depIdxs = []int32{
	2, // 0: interaction.v1.InteractRequest.study_method:type_name -> shared.v1.StudyMethod
	3, // 1: interaction.v1.InteractRequest.interaction_type:type_name -> shared.v1.InteractionType
	4, // 2: interaction.v1.InteractRequest.deck_assignment:type_name -> shared.v1.DeckAssignment
	5, // 3: interaction.v1.InteractResponse.question:type_name -> shared.v1.Question
	0, // 4: interaction.v1.InteractionService.Interact:input_type -> interaction.v1.InteractRequest
	1, // 5: interaction.v1.InteractionService.Interact:output_type -> interaction.v1.InteractResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_v1_interaction_interaction_proto_init() }
func file_v1_interaction_interaction_proto_init() {
	if File_v1_interaction_interaction_proto != nil {
		return
	}
	file_v1_interaction_interaction_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_interaction_interaction_proto_rawDesc), len(file_v1_interaction_interaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_interaction_interaction_proto_goTypes,
		DependencyIndexes: file_v1_interaction_interaction_proto_depIdxs,
		MessageInfos:      file_v1_interaction_interaction_proto_msgTypes,
	}.Build()
	File_v1_interaction_interaction_proto = out.File
	file_v1_interaction_interaction_proto_goTypes = nil
	file_v1_interaction_interaction_proto_depIdxs = nil
}
