// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/tag/tag.proto

package tagv1

import (
	shared "github.com/studyguides-com/study-guides-api/api/v1/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagRequest) Reset() {
	*x = GetTagRequest{}
	mi := &file_v1_tag_tag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagRequest) ProtoMessage() {}

func (x *GetTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tag_tag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagRequest.ProtoReflect.Descriptor instead.
func (*GetTagRequest) Descriptor() ([]byte, []int) {
	return file_v1_tag_tag_proto_rawDescGZIP(), []int{0}
}

func (x *GetTagRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListTagsByParentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentId      string                 `protobuf:"bytes,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsByParentRequest) Reset() {
	*x = ListTagsByParentRequest{}
	mi := &file_v1_tag_tag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsByParentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsByParentRequest) ProtoMessage() {}

func (x *ListTagsByParentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tag_tag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsByParentRequest.ProtoReflect.Descriptor instead.
func (*ListTagsByParentRequest) Descriptor() ([]byte, []int) {
	return file_v1_tag_tag_proto_rawDescGZIP(), []int{1}
}

func (x *ListTagsByParentRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *ListTagsByParentRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTagsByParentRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListTagsByTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsByTypeRequest) Reset() {
	*x = ListTagsByTypeRequest{}
	mi := &file_v1_tag_tag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsByTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsByTypeRequest) ProtoMessage() {}

func (x *ListTagsByTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tag_tag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsByTypeRequest.ProtoReflect.Descriptor instead.
func (*ListTagsByTypeRequest) Descriptor() ([]byte, []int) {
	return file_v1_tag_tag_proto_rawDescGZIP(), []int{2}
}

func (x *ListTagsByTypeRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListTagsByTypeRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTagsByTypeRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListRootTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRootTagsRequest) Reset() {
	*x = ListRootTagsRequest{}
	mi := &file_v1_tag_tag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRootTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRootTagsRequest) ProtoMessage() {}

func (x *ListRootTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tag_tag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRootTagsRequest.ProtoReflect.Descriptor instead.
func (*ListRootTagsRequest) Descriptor() ([]byte, []int) {
	return file_v1_tag_tag_proto_rawDescGZIP(), []int{3}
}

func (x *ListRootTagsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRootTagsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*shared.Tag          `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsResponse) Reset() {
	*x = ListTagsResponse{}
	mi := &file_v1_tag_tag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsResponse) ProtoMessage() {}

func (x *ListTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tag_tag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsResponse.ProtoReflect.Descriptor instead.
func (*ListTagsResponse) Descriptor() ([]byte, []int) {
	return file_v1_tag_tag_proto_rawDescGZIP(), []int{4}
}

func (x *ListTagsResponse) GetTags() []*shared.Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ListTagsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_v1_tag_tag_proto protoreflect.FileDescriptor

const file_v1_tag_tag_proto_rawDesc = "" +
	"\n" +
	"\x10v1/tag/tag.proto\x12\x06tag.v1\x1a\x13v1/shared/tag.proto\"\x1f\n" +
	"\rGetTagRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"r\n" +
	"\x17ListTagsByParentRequest\x12\x1b\n" +
	"\tparent_id\x18\x01 \x01(\tR\bparentId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"g\n" +
	"\x15ListTagsByTypeRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"Q\n" +
	"\x13ListRootTagsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"^\n" +
	"\x10ListTagsResponse\x12\"\n" +
	"\x04tags\x18\x01 \x03(\v2\x0e.shared.v1.TagR\x04tags\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\xa6\x02\n" +
	"\n" +
	"TagService\x121\n" +
	"\x06GetTag\x12\x15.tag.v1.GetTagRequest\x1a\x0e.shared.v1.Tag\"\x00\x12O\n" +
	"\x10ListTagsByParent\x12\x1f.tag.v1.ListTagsByParentRequest\x1a\x18.tag.v1.ListTagsResponse\"\x00\x12K\n" +
	"\x0eListTagsByType\x12\x1d.tag.v1.ListTagsByTypeRequest\x1a\x18.tag.v1.ListTagsResponse\"\x00\x12G\n" +
	"\fListRootTags\x12\x1b.tag.v1.ListRootTagsRequest\x1a\x18.tag.v1.ListTagsResponse\"\x00B>Z<github.com/studyguides-com/study-guides-api/api/v1/tag;tagv1b\x06proto3"

var (
	file_v1_tag_tag_proto_rawDescOnce sync.Once
	file_v1_tag_tag_proto_rawDescData []byte
)

func file_v1_tag_tag_proto_rawDescGZIP() []byte {
	file_v1_tag_tag_proto_rawDescOnce.Do(func() {
		file_v1_tag_tag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_tag_tag_proto_rawDesc), len(file_v1_tag_tag_proto_rawDesc)))
	})
	return file_v1_tag_tag_proto_rawDescData
}

var file_v1_tag_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_v1_tag_tag_proto_goTypes = []any{
	(*GetTagRequest)(nil),           // 0: tag.v1.GetTagRequest
	(*ListTagsByParentRequest)(nil), // 1: tag.v1.ListTagsByParentRequest
	(*ListTagsByTypeRequest)(nil),   // 2: tag.v1.ListTagsByTypeRequest
	(*ListRootTagsRequest)(nil),     // 3: tag.v1.ListRootTagsRequest
	(*ListTagsResponse)(nil),        // 4: tag.v1.ListTagsResponse
	(*shared.Tag)(nil),              // 5: shared.v1.Tag
}
var file_v1_tag_tag_proto_depIdxs = []int32{
	5, // 0: tag.v1.ListTagsResponse.tags:type_name -> shared.v1.Tag
	0, // 1: tag.v1.TagService.GetTag:input_type -> tag.v1.GetTagRequest
	1, // 2: tag.v1.TagService.ListTagsByParent:input_type -> tag.v1.ListTagsByParentRequest
	2, // 3: tag.v1.TagService.ListTagsByType:input_type -> tag.v1.ListTagsByTypeRequest
	3, // 4: tag.v1.TagService.ListRootTags:input_type -> tag.v1.ListRootTagsRequest
	5, // 5: tag.v1.TagService.GetTag:output_type -> shared.v1.Tag
	4, // 6: tag.v1.TagService.ListTagsByParent:output_type -> tag.v1.ListTagsResponse
	4, // 7: tag.v1.TagService.ListTagsByType:output_type -> tag.v1.ListTagsResponse
	4, // 8: tag.v1.TagService.ListRootTags:output_type -> tag.v1.ListTagsResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_tag_tag_proto_init() }
func file_v1_tag_tag_proto_init() {
	if File_v1_tag_tag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_tag_tag_proto_rawDesc), len(file_v1_tag_tag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_tag_tag_proto_goTypes,
		DependencyIndexes: file_v1_tag_tag_proto_depIdxs,
		MessageInfos:      file_v1_tag_tag_proto_msgTypes,
	}.Build()
	File_v1_tag_tag_proto = out.File
	file_v1_tag_tag_proto_goTypes = nil
	file_v1_tag_tag_proto_depIdxs = nil
}
