// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/admin/admin.proto

package adminv1

import (
	shared "github.com/studyguides-com/study-guides-api/api/v1/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewTagAdminRequest struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Name          string                         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Hash          string                         `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Type          shared.TagType                 `protobuf:"varint,3,opt,name=type,proto3,enum=shared.v1.TagType" json:"type,omitempty"`
	ParentId      string                         `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Rating        shared.ContentRating           `protobuf:"varint,5,opt,name=rating,proto3,enum=shared.v1.ContentRating" json:"rating,omitempty"`
	Descriptors   []shared.ContentDescriptorType `protobuf:"varint,6,rep,packed,name=descriptors,proto3,enum=shared.v1.ContentDescriptorType" json:"descriptors,omitempty"`
	MetaTags      []string                       `protobuf:"bytes,7,rep,name=meta_tags,json=metaTags,proto3" json:"meta_tags,omitempty"`
	ParserType    shared.ParserType              `protobuf:"varint,8,opt,name=parser_type,json=parserType,proto3,enum=shared.v1.ParserType" json:"parser_type,omitempty"`
	Metadata      map[string]string              `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewTagAdminRequest) Reset() {
	*x = NewTagAdminRequest{}
	mi := &file_v1_admin_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewTagAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewTagAdminRequest) ProtoMessage() {}

func (x *NewTagAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewTagAdminRequest.ProtoReflect.Descriptor instead.
func (*NewTagAdminRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_admin_proto_rawDescGZIP(), []int{0}
}

func (x *NewTagAdminRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NewTagAdminRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *NewTagAdminRequest) GetType() shared.TagType {
	if x != nil {
		return x.Type
	}
	return shared.TagType(0)
}

func (x *NewTagAdminRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *NewTagAdminRequest) GetRating() shared.ContentRating {
	if x != nil {
		return x.Rating
	}
	return shared.ContentRating(0)
}

func (x *NewTagAdminRequest) GetDescriptors() []shared.ContentDescriptorType {
	if x != nil {
		return x.Descriptors
	}
	return nil
}

func (x *NewTagAdminRequest) GetMetaTags() []string {
	if x != nil {
		return x.MetaTags
	}
	return nil
}

func (x *NewTagAdminRequest) GetParserType() shared.ParserType {
	if x != nil {
		return x.ParserType
	}
	return shared.ParserType(0)
}

func (x *NewTagAdminRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type NewTagAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           *shared.Tag            `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewTagAdminResponse) Reset() {
	*x = NewTagAdminResponse{}
	mi := &file_v1_admin_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewTagAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewTagAdminResponse) ProtoMessage() {}

func (x *NewTagAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewTagAdminResponse.ProtoReflect.Descriptor instead.
func (*NewTagAdminResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_admin_proto_rawDescGZIP(), []int{1}
}

func (x *NewTagAdminResponse) GetTag() *shared.Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

type KillUserAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillUserAdminRequest) Reset() {
	*x = KillUserAdminRequest{}
	mi := &file_v1_admin_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillUserAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillUserAdminRequest) ProtoMessage() {}

func (x *KillUserAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillUserAdminRequest.ProtoReflect.Descriptor instead.
func (*KillUserAdminRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_admin_proto_rawDescGZIP(), []int{2}
}

func (x *KillUserAdminRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type KillUserAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillUserAdminResponse) Reset() {
	*x = KillUserAdminResponse{}
	mi := &file_v1_admin_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillUserAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillUserAdminResponse) ProtoMessage() {}

func (x *KillUserAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillUserAdminResponse.ProtoReflect.Descriptor instead.
func (*KillUserAdminResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_admin_proto_rawDescGZIP(), []int{3}
}

func (x *KillUserAdminResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_v1_admin_admin_proto protoreflect.FileDescriptor

const file_v1_admin_admin_proto_rawDesc = "" +
	"\n" +
	"\x14v1/admin/admin.proto\x12\badmin.v1\x1a\x17v1/shared/tagtype.proto\x1a\x1dv1/shared/contentrating.proto\x1a%v1/shared/contentdescriptortype.proto\x1a\x1av1/shared/parsertype.proto\x1a\x13v1/shared/tag.proto\"\xd1\x03\n" +
	"\x12NewTagAdminRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12&\n" +
	"\x04type\x18\x03 \x01(\x0e2\x12.shared.v1.TagTypeR\x04type\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\tR\bparentId\x120\n" +
	"\x06rating\x18\x05 \x01(\x0e2\x18.shared.v1.ContentRatingR\x06rating\x12B\n" +
	"\vdescriptors\x18\x06 \x03(\x0e2 .shared.v1.ContentDescriptorTypeR\vdescriptors\x12\x1b\n" +
	"\tmeta_tags\x18\a \x03(\tR\bmetaTags\x126\n" +
	"\vparser_type\x18\b \x01(\x0e2\x15.shared.v1.ParserTypeR\n" +
	"parserType\x12F\n" +
	"\bmetadata\x18\t \x03(\v2*.admin.v1.NewTagAdminRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"7\n" +
	"\x13NewTagAdminResponse\x12 \n" +
	"\x03tag\x18\x01 \x01(\v2\x0e.shared.v1.TagR\x03tag\",\n" +
	"\x14KillUserAdminRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"'\n" +
	"\x15KillUserAdminResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2]\n" +
	"\fAdminService\x12M\n" +
	"\bKillUser\x12\x1e.admin.v1.KillUserAdminRequest\x1a\x1f.admin.v1.KillUserAdminResponse\"\x00BBZ@github.com/studyguides-com/study-guides-api/api/v1/admin;adminv1b\x06proto3"

var (
	file_v1_admin_admin_proto_rawDescOnce sync.Once
	file_v1_admin_admin_proto_rawDescData []byte
)

func file_v1_admin_admin_proto_rawDescGZIP() []byte {
	file_v1_admin_admin_proto_rawDescOnce.Do(func() {
		file_v1_admin_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_admin_admin_proto_rawDesc), len(file_v1_admin_admin_proto_rawDesc)))
	})
	return file_v1_admin_admin_proto_rawDescData
}

var file_v1_admin_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_v1_admin_admin_proto_goTypes = []any{
	(*NewTagAdminRequest)(nil),        // 0: admin.v1.NewTagAdminRequest
	(*NewTagAdminResponse)(nil),       // 1: admin.v1.NewTagAdminResponse
	(*KillUserAdminRequest)(nil),      // 2: admin.v1.KillUserAdminRequest
	(*KillUserAdminResponse)(nil),     // 3: admin.v1.KillUserAdminResponse
	nil,                               // 4: admin.v1.NewTagAdminRequest.MetadataEntry
	(shared.TagType)(0),               // 5: shared.v1.TagType
	(shared.ContentRating)(0),         // 6: shared.v1.ContentRating
	(shared.ContentDescriptorType)(0), // 7: shared.v1.ContentDescriptorType
	(shared.ParserType)(0),            // 8: shared.v1.ParserType
	(*shared.Tag)(nil),                // 9: shared.v1.Tag
}
var file_v1_admin_admin_proto_depIdxs = []int32{
	5, // 0: admin.v1.NewTagAdminRequest.type:type_name -> shared.v1.TagType
	6, // 1: admin.v1.NewTagAdminRequest.rating:type_name -> shared.v1.ContentRating
	7, // 2: admin.v1.NewTagAdminRequest.descriptors:type_name -> shared.v1.ContentDescriptorType
	8, // 3: admin.v1.NewTagAdminRequest.parser_type:type_name -> shared.v1.ParserType
	4, // 4: admin.v1.NewTagAdminRequest.metadata:type_name -> admin.v1.NewTagAdminRequest.MetadataEntry
	9, // 5: admin.v1.NewTagAdminResponse.tag:type_name -> shared.v1.Tag
	2, // 6: admin.v1.AdminService.KillUser:input_type -> admin.v1.KillUserAdminRequest
	3, // 7: admin.v1.AdminService.KillUser:output_type -> admin.v1.KillUserAdminResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_v1_admin_admin_proto_init() }
func file_v1_admin_admin_proto_init() {
	if File_v1_admin_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_admin_admin_proto_rawDesc), len(file_v1_admin_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_admin_admin_proto_goTypes,
		DependencyIndexes: file_v1_admin_admin_proto_depIdxs,
		MessageInfos:      file_v1_admin_admin_proto_msgTypes,
	}.Build()
	File_v1_admin_admin_proto = out.File
	file_v1_admin_admin_proto_goTypes = nil
	file_v1_admin_admin_proto_depIdxs = nil
}
