// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/devops/devops.proto

package devopsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeploymentStatus int32

const (
	DeploymentStatus_UNKNOWN  DeploymentStatus = 0
	DeploymentStatus_PENDING  DeploymentStatus = 1
	DeploymentStatus_BUILDING DeploymentStatus = 2
	DeploymentStatus_ACTIVE   DeploymentStatus = 3
	DeploymentStatus_ERROR    DeploymentStatus = 4
	DeploymentStatus_CANCELED DeploymentStatus = 5
)

// Enum value maps for DeploymentStatus.
var (
	DeploymentStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "PENDING",
		2: "BUILDING",
		3: "ACTIVE",
		4: "ERROR",
		5: "CANCELED",
	}
	DeploymentStatus_value = map[string]int32{
		"UNKNOWN":  0,
		"PENDING":  1,
		"BUILDING": 2,
		"ACTIVE":   3,
		"ERROR":    4,
		"CANCELED": 5,
	}
)

func (x DeploymentStatus) Enum() *DeploymentStatus {
	p := new(DeploymentStatus)
	*p = x
	return p
}

func (x DeploymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeploymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_devops_devops_proto_enumTypes[0].Descriptor()
}

func (DeploymentStatus) Type() protoreflect.EnumType {
	return &file_v1_devops_devops_proto_enumTypes[0]
}

func (x DeploymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeploymentStatus.Descriptor instead.
func (DeploymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_devops_devops_proto_rawDescGZIP(), []int{0}
}

type DeployRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"` // if true, triggers a rebuild even if unchanged
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployRequest) Reset() {
	*x = DeployRequest{}
	mi := &file_v1_devops_devops_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployRequest) ProtoMessage() {}

func (x *DeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_devops_devops_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployRequest.ProtoReflect.Descriptor instead.
func (*DeployRequest) Descriptor() ([]byte, []int) {
	return file_v1_devops_devops_proto_rawDescGZIP(), []int{0}
}

func (x *DeployRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *DeployRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type DeployResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployResponse) Reset() {
	*x = DeployResponse{}
	mi := &file_v1_devops_devops_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployResponse) ProtoMessage() {}

func (x *DeployResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_devops_devops_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployResponse.ProtoReflect.Descriptor instead.
func (*DeployResponse) Descriptor() ([]byte, []int) {
	return file_v1_devops_devops_proto_rawDescGZIP(), []int{1}
}

func (x *DeployResponse) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

type ListDeploymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeploymentsRequest) Reset() {
	*x = ListDeploymentsRequest{}
	mi := &file_v1_devops_devops_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeploymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeploymentsRequest) ProtoMessage() {}

func (x *ListDeploymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_devops_devops_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeploymentsRequest.ProtoReflect.Descriptor instead.
func (*ListDeploymentsRequest) Descriptor() ([]byte, []int) {
	return file_v1_devops_devops_proto_rawDescGZIP(), []int{2}
}

func (x *ListDeploymentsRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type ListDeploymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployments   []*Deployment          `protobuf:"bytes,1,rep,name=deployments,proto3" json:"deployments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeploymentsResponse) Reset() {
	*x = ListDeploymentsResponse{}
	mi := &file_v1_devops_devops_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeploymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeploymentsResponse) ProtoMessage() {}

func (x *ListDeploymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_devops_devops_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeploymentsResponse.ProtoReflect.Descriptor instead.
func (*ListDeploymentsResponse) Descriptor() ([]byte, []int) {
	return file_v1_devops_devops_proto_rawDescGZIP(), []int{3}
}

func (x *ListDeploymentsResponse) GetDeployments() []*Deployment {
	if x != nil {
		return x.Deployments
	}
	return nil
}

type GetDeploymentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	DeploymentId  string                 `protobuf:"bytes,2,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeploymentStatusRequest) Reset() {
	*x = GetDeploymentStatusRequest{}
	mi := &file_v1_devops_devops_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeploymentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeploymentStatusRequest) ProtoMessage() {}

func (x *GetDeploymentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_devops_devops_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeploymentStatusRequest.ProtoReflect.Descriptor instead.
func (*GetDeploymentStatusRequest) Descriptor() ([]byte, []int) {
	return file_v1_devops_devops_proto_rawDescGZIP(), []int{4}
}

func (x *GetDeploymentStatusRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GetDeploymentStatusRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

type GetDeploymentStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployment    *Deployment            `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeploymentStatusResponse) Reset() {
	*x = GetDeploymentStatusResponse{}
	mi := &file_v1_devops_devops_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeploymentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeploymentStatusResponse) ProtoMessage() {}

func (x *GetDeploymentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_devops_devops_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeploymentStatusResponse.ProtoReflect.Descriptor instead.
func (*GetDeploymentStatusResponse) Descriptor() ([]byte, []int) {
	return file_v1_devops_devops_proto_rawDescGZIP(), []int{5}
}

func (x *GetDeploymentStatusResponse) GetDeployment() *Deployment {
	if x != nil {
		return x.Deployment
	}
	return nil
}

type Deployment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Status        DeploymentStatus       `protobuf:"varint,3,opt,name=status,proto3,enum=devops.v1.DeploymentStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deployment) Reset() {
	*x = Deployment{}
	mi := &file_v1_devops_devops_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deployment) ProtoMessage() {}

func (x *Deployment) ProtoReflect() protoreflect.Message {
	mi := &file_v1_devops_devops_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deployment.ProtoReflect.Descriptor instead.
func (*Deployment) Descriptor() ([]byte, []int) {
	return file_v1_devops_devops_proto_rawDescGZIP(), []int{6}
}

func (x *Deployment) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *Deployment) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *Deployment) GetStatus() DeploymentStatus {
	if x != nil {
		return x.Status
	}
	return DeploymentStatus_UNKNOWN
}

func (x *Deployment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type RollbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	DeploymentId  string                 `protobuf:"bytes,2,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"` // ID of the deployment to roll back to
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackRequest) Reset() {
	*x = RollbackRequest{}
	mi := &file_v1_devops_devops_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackRequest) ProtoMessage() {}

func (x *RollbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_devops_devops_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackRequest.ProtoReflect.Descriptor instead.
func (*RollbackRequest) Descriptor() ([]byte, []int) {
	return file_v1_devops_devops_proto_rawDescGZIP(), []int{7}
}

func (x *RollbackRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *RollbackRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

type RollbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"` // new deployment ID created by rollback
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackResponse) Reset() {
	*x = RollbackResponse{}
	mi := &file_v1_devops_devops_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackResponse) ProtoMessage() {}

func (x *RollbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_devops_devops_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackResponse.ProtoReflect.Descriptor instead.
func (*RollbackResponse) Descriptor() ([]byte, []int) {
	return file_v1_devops_devops_proto_rawDescGZIP(), []int{8}
}

func (x *RollbackResponse) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

var File_v1_devops_devops_proto protoreflect.FileDescriptor

const file_v1_devops_devops_proto_rawDesc = "" +
	"\n" +
	"\x16v1/devops/devops.proto\x12\tdevops.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"<\n" +
	"\rDeployRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"5\n" +
	"\x0eDeployResponse\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\"/\n" +
	"\x16ListDeploymentsRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\"R\n" +
	"\x17ListDeploymentsResponse\x127\n" +
	"\vdeployments\x18\x01 \x03(\v2\x15.devops.v1.DeploymentR\vdeployments\"X\n" +
	"\x1aGetDeploymentStatusRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12#\n" +
	"\rdeployment_id\x18\x02 \x01(\tR\fdeploymentId\"T\n" +
	"\x1bGetDeploymentStatusResponse\x125\n" +
	"\n" +
	"deployment\x18\x01 \x01(\v2\x15.devops.v1.DeploymentR\n" +
	"deployment\"\xb8\x01\n" +
	"\n" +
	"Deployment\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x123\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1b.devops.v1.DeploymentStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"M\n" +
	"\x0fRollbackRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12#\n" +
	"\rdeployment_id\x18\x02 \x01(\tR\fdeploymentId\"7\n" +
	"\x10RollbackResponse\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId*_\n" +
	"\x10DeploymentStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\f\n" +
	"\bBUILDING\x10\x02\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x04\x12\f\n" +
	"\bCANCELED\x10\x052\xd3\x02\n" +
	"\rDevopsService\x12=\n" +
	"\x06Deploy\x12\x18.devops.v1.DeployRequest\x1a\x19.devops.v1.DeployResponse\x12C\n" +
	"\bRollback\x12\x1a.devops.v1.RollbackRequest\x1a\x1b.devops.v1.RollbackResponse\x12X\n" +
	"\x0fListDeployments\x12!.devops.v1.ListDeploymentsRequest\x1a\".devops.v1.ListDeploymentsResponse\x12d\n" +
	"\x13GetDeploymentStatus\x12%.devops.v1.GetDeploymentStatusRequest\x1a&.devops.v1.GetDeploymentStatusResponseBDZBgithub.com/studyguides-com/study-guides-api/api/v1/devops;devopsv1b\x06proto3"

var (
	file_v1_devops_devops_proto_rawDescOnce sync.Once
	file_v1_devops_devops_proto_rawDescData []byte
)

func file_v1_devops_devops_proto_rawDescGZIP() []byte {
	file_v1_devops_devops_proto_rawDescOnce.Do(func() {
		file_v1_devops_devops_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_devops_devops_proto_rawDesc), len(file_v1_devops_devops_proto_rawDesc)))
	})
	return file_v1_devops_devops_proto_rawDescData
}

var file_v1_devops_devops_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_devops_devops_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_v1_devops_devops_proto_goTypes = []any{
	(DeploymentStatus)(0),               // 0: devops.v1.DeploymentStatus
	(*DeployRequest)(nil),               // 1: devops.v1.DeployRequest
	(*DeployResponse)(nil),              // 2: devops.v1.DeployResponse
	(*ListDeploymentsRequest)(nil),      // 3: devops.v1.ListDeploymentsRequest
	(*ListDeploymentsResponse)(nil),     // 4: devops.v1.ListDeploymentsResponse
	(*GetDeploymentStatusRequest)(nil),  // 5: devops.v1.GetDeploymentStatusRequest
	(*GetDeploymentStatusResponse)(nil), // 6: devops.v1.GetDeploymentStatusResponse
	(*Deployment)(nil),                  // 7: devops.v1.Deployment
	(*RollbackRequest)(nil),             // 8: devops.v1.RollbackRequest
	(*RollbackResponse)(nil),            // 9: devops.v1.RollbackResponse
	(*timestamppb.Timestamp)(nil),       // 10: google.protobuf.Timestamp
}
var file_v1_devops_devops_proto_depIdxs = []int32{
	7,  // 0: devops.v1.ListDeploymentsResponse.deployments:type_name -> devops.v1.Deployment
	7,  // 1: devops.v1.GetDeploymentStatusResponse.deployment:type_name -> devops.v1.Deployment
	0,  // 2: devops.v1.Deployment.status:type_name -> devops.v1.DeploymentStatus
	10, // 3: devops.v1.Deployment.created_at:type_name -> google.protobuf.Timestamp
	1,  // 4: devops.v1.DevopsService.Deploy:input_type -> devops.v1.DeployRequest
	8,  // 5: devops.v1.DevopsService.Rollback:input_type -> devops.v1.RollbackRequest
	3,  // 6: devops.v1.DevopsService.ListDeployments:input_type -> devops.v1.ListDeploymentsRequest
	5,  // 7: devops.v1.DevopsService.GetDeploymentStatus:input_type -> devops.v1.GetDeploymentStatusRequest
	2,  // 8: devops.v1.DevopsService.Deploy:output_type -> devops.v1.DeployResponse
	9,  // 9: devops.v1.DevopsService.Rollback:output_type -> devops.v1.RollbackResponse
	4,  // 10: devops.v1.DevopsService.ListDeployments:output_type -> devops.v1.ListDeploymentsResponse
	6,  // 11: devops.v1.DevopsService.GetDeploymentStatus:output_type -> devops.v1.GetDeploymentStatusResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_v1_devops_devops_proto_init() }
func file_v1_devops_devops_proto_init() {
	if File_v1_devops_devops_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_devops_devops_proto_rawDesc), len(file_v1_devops_devops_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_devops_devops_proto_goTypes,
		DependencyIndexes: file_v1_devops_devops_proto_depIdxs,
		EnumInfos:         file_v1_devops_devops_proto_enumTypes,
		MessageInfos:      file_v1_devops_devops_proto_msgTypes,
	}.Build()
	File_v1_devops_devops_proto = out.File
	file_v1_devops_devops_proto_goTypes = nil
	file_v1_devops_devops_proto_depIdxs = nil
}
